### ISSUE TITLE
Update Keycloak version

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#1003]
**Motivation**:
One external Renku deployment needs to update keycloak to a version higher than `8.0.1`, current latest version is `9.0.2`.

~Furthermore, `stable` charts are deprecated and we should update to `codecentric` charts.~
This has been adapted in the meantime.

**Needed change in requirements**
https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/requirements.yaml#L31
Current 
```
- name: keycloak
  version: 4.10.1
  repository: "@stable"
  condition: keycloak.enabled
```
desired:
```
- name: keycloak
  version: 7.5.0
  repository: "@codecentric"
  condition: keycloak.enabled
```
We also need to add codecentric to helm `helm repo add codecentric https://codecentric.github.io/helm-charts`

ref: https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/Chart.yaml

**Priority**
Not urgent, but needed in the next few weeks.

Assigning @ableuler since this might need gateway adaptations.

cc @nbarierre

**Comment by pameladelgado** [comment]
I tested a RenkuLab deployment with newer images `8.0.2` and `9.0.3` and it works fine.
For now, deployments that have a stand-alone keycloak can update until `9.0.3` without further modifications.
However, the charts need to be upgraded and they would not be backwards compatible (see https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#upgrading).
``` 
Warning: Merging destination map for chart 'keycloak'. The destination item 'livenessProbe' is a table
 and ignoring the source 'livenessProbe' as it has a non-table value of: httpGet:
  path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/
  port: http
initialDelaySeconds: 300
timeoutSeconds: 5
Error: render error in "renku/charts/keycloak/templates/statefulset.yaml": template: renku/charts
/keycloak/templates/statefulset.yaml:141:20: executing "renku/charts/keycloak/templates
/statefulset.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by ableuler** [comment]
> I tested a RenkuLab deployment with newer images `8.0.2` and `9.0.3` and it works fine.

Thanks for testing this 👍 ! I agree that we should upgrade both chart and image sooner rather than later. See also #1273.

**Comment by ableuler** [comment]
By now, the latest chart version is `9.8.1` which uses uses the app version `11.0.2`. In the chart `9.0.0` release, the values file has been completely restructured. Also, the way how we can provide an existing secret containing the DB access credentials has changed. Upgrading this dependency and especially testing and documenting the migration of existing RenkuLab deployments has become more difficult but also more urgent.
