### ISSUE TITLE
docs: improve documentation for how to add documentation

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#1014]
**Is your feature request related to a problem? Please describe.**
One of the reasons it's hard to write new documentation and update old documentation is because the documentation isn't well documented!

**Describe the solution you'd like**
Better document how to add documentation.

**Additional context**
One of the other reasons it's hard to add and update docs is because the organizational structure of the docs is intense. Other issues are open for this.

**Comment by gavin-k-lee** [comment]
Addressed here: 

https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/1655767045/Quick-start+guide+to+writing+renku+documentation
