### ISSUE TITLE
Support more recent k8s versions

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1038]
Currently, we're failing for anything >= 1.16 (released in July 2019!) because we're still using the deprecated `apps/v1beta2` API. Also, we should document somewhere which k8s versions we support.

**Comment by pameladelgado** [comment]
Closing, Renku is able to run on `v1.19`. There is a table of officially supported versions in our [readthedocs](https://renku.readthedocs.io/en/latest/admin/index.html#officially-supported-versions) (which admittedly needs to be updated).
