### ISSUE TITLE
Underscore in username causes the image build to fail

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#1128]
Underscores `_` seem to be allowed in email usernames, they are not, however, allowed in docker image names. If a username has underscores, the image build will fail. We should handle this somehow but it's not obvious how if the user is allowed to pick that username.

**Comment by ableuler** [comment]
I can not reproduce this problem. Underscores in docker image names seem to be accepted, try
```
docker pull registry.renkulab.io/test_unserscore/public_test:d24424b
```
for example.

**Comment by rokroskar** [comment]
Did you try changing your username?

**Comment by rokroskar** [comment]
This definitely failed in May for a student in the SIB course. It's possible something has changed in the meantime in the docker registry and/or gitlab

**Comment by ableuler** [comment]
Closing this issue since the problem can not be reproduced at the moment. Let's keep it in the back of our heads though and reopen the issue if we see a similar problem.
