### ISSUE TITLE
remove unneeded gitlab admin token usage

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#1177]
GitLab admin tokens are not needed anymore for spawning user interactive sessions (see https://github.com/SwissDataScienceCenter/renku-notebooks/pull/327). We should remove all references and uses of these admin tokens from the charts in this repository.

**Comment by gavin-k-lee** [comment]
Effectively closed right?

**Comment by pameladelgado** [comment]
> Effectively closed right?

Yes, we dont make reference to those tokens anymore in our charts.
