### ISSUE TITLE
Removing renku CLI version installation from acceptance test

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku#1330]
As a renku maintainer I do not want the acceptance tests to override my local installation of renku CLI. 

**Acceptance criteria**
- The tests should use the same python/renku version as the one in the DockerFile.
- The installation of python/renku and its dependencies should be done with a virtual env.

![FlightsTutorial](https://github.com/SwissDataScienceCenter/renku/blob/master/tests/src/test/scala/ch/renku/acceptancetests/workflows/FlightsTutorial.scala)

**Comment by travissarles** [comment]
**Problem**: 
`
{"message":"API rate limit exceeded for 188.62.144.27. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}`

**Solution**: 
Wait

**Comment by travissarles** [comment]
Using virtualenv to avoid messing with the system environment for acceptance tests. Need to consider the version of virtualenv.

**Comment by travissarles** [comment]
Added a script for detecting the global version of virtualenv and replacing it if it's not the correct version.

**Comment by travissarles** [comment]
**Problem**
`git push failed with:
[info] remote: HTTP Basic: Access denied
[info] fatal: Authentication failed for 'https://dev.renku.ch/gitlab/travis.lee/test_2020_08_04_1825_23.git/'`

**Solution**
Go to the Gitlab UI and click on the warning that says you need to set your password

**Comment by travissarles** [comment]
**Problem:**
Pandas not found
`[info] File "/usr/local/lib/python3.8/site-packages/papermill/execute.py", line 192, in raise_for_execution_errors
[info] raise error
[info] papermill.exceptions.PapermillExecutionError:
[info] ---------------------------------------------------------------------------
[info] Exception encountered at "In [1]":
[info] ---------------------------------------------------------------------------
[info] ModuleNotFoundError                       Traceback (most recent call last)
[info] <ipython-input-1-7dd3504c366f> in <module>
[info] ----> 1 import pandas as pd
[info] ModuleNotFoundError: No module named 'pandas'`

**Solution:**
Make sure the virtualenv is activated or the path to the ./venv/bin is in the system path

**Comment by jachro** [comment]
Done as part of #1389
