### ISSUE TITLE
Not able to run renku docker image 

### ISSUE THREAD

**Issue by Rohit-Satyam** [SwissDataScienceCenter/renku#1364]
**Describe the bug**
Tried running the renkulab docker image but couldn't run 

`docker run -v "/home/iitm/rohit_satyam/temp-lib:/downloads" -p 8787:8787 --name=renku -it renku/renkulab-py:3.7-0c91990`

`fatal: repository '@//renku-env.git' does not exist
find: ‘/tmp/renku-env’: No such file or directory
Executing the command: jupyterhub-singleuser --ip=0.0.0.0
[W 2020-08-12 13:32:43.006 SingleUserNotebookApp configurable:168] Config option open_browser not recognized by SingleUserNotebookApp.  Did you mean browser?
JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?
`

**Comment by ableuler** [comment]
Hi Rohit-Satyam,
to run this image locally you have to append `jupyter lab` to your command? This will overwrite the default command of the docker image which tries to connect to a jupyterhub.
