### ISSUE TITLE
Migrate CD deployment to helm 3

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1393]
Before simply using helm 3 in the CD pipeline, we have to find out and test how to maintain the history of the deployment as this would be valuable when doing the same in production.

**Comment by pameladelgado** [comment]
> we have to find out and test how to maintain the history of the deployment

Using the [2to3 plugin](https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/) should be enough for our needs. The command `helm3 2to3 convert renku` should be executed right before merging the PR that adapts the corresponding github action.

**Comment by ableuler** [comment]
> The command `helm3 2to3 convert renku` should be executed right before merging the PR that adapts the corresponding github action.

Agree - per default this will keep the history for the last 10 versions - I think that's ok for our purpose. The `helm3 2to3 cleanup --name renku` command after the conversion is useful too as it will remove the helm 2 release without deleting its resources.
