### ISSUE TITLE
Add network policies to renku charts

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1435]
Network policies are a way to limit the communication between pods and and the outside world or in-between pods. We are currently using them only to limit access to the Redis stores. It would be good practice to use network policies and only allow the necessary communication between pods. In particular, the pods running user code should be separated from the platform pods through network policies.

**Comment by aledegano** [comment]
While this ticket was created some time ago it is more important now than ever. We will schedule it in the next YAT sprint.

**Comment by aledegano** [comment]
Some network policies were created. We should now verify if those are sufficient (improve if not) and close this issue.

**Comment by ableuler** [comment]
Note that the user pods are in fact separated from the rest at this point
