### ISSUE TITLE
tests: create a scenario around git workflow

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku#157]
- [ ] create a Renga project locally
- [ ] push project to gitlab
- [ ] create a branch
- [ ] create a PR
- [ ] get jupyterhub URL from the environment
- [ ] open a link and create a notebook
- [ ] ... TBD

--
addresses #148 
related to https://github.com/SwissDataScienceCenter/renga-ui/issues/132

**Comment by rokroskar** [comment]
We should use @ciyer's demo scenario, data and code

**Comment by leafty** [comment]
Closing this as we have https://github.com/SwissDataScienceCenter/renku-demo.
