### ISSUE TITLE
chore: update deprecated github action syntax

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#1615]
Handling of environment variables in GitHub actions has changed due to a security vulnerability - see [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

We should update the CI in all repos to use the new syntax described [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)

**Comment by lorenzo-cavazzi** [comment]
closed by #1687
