### ISSUE TITLE
Specify a target registry image for interactive environments

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku#1646]
We want to allow users to provide a specific registry image to be used for starting interactive environments. That would avoid creating new images when not needed, speeding up the GitLab CI (ideally no actions at all), and saving space at the same time.

**Comment by rokroskar** [comment]
Is this a duplicate of #1611? cc @ableuler

**Comment by ableuler** [comment]
Yep. @lorenzo-cavazzi feel free to merge the information and issues of the two epics into one in whatever form makes most sense to you.

**Comment by lorenzo-cavazzi** [comment]
Ouch, sorry about that, I really missed the first epic :sweat_smile: 
I'll merge the relevant pieces and discard the rest

**Comment by lorenzo-cavazzi** [comment]
Ok I close this since it's mostly a duplicate of #1611 .
I've added a comment there. Sorry for the confusion.
