### ISSUE TITLE
Investigate git clone failures over https

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1678]
Cloning larger repos over https fails sporadically. See for example [this thread on gitter](https://gitter.im/SwissDataScienceCenter/renku?at=5fabc4c9c10273610afbd769).

Most likely related is [this issue](https://github.com/SwissDataScienceCenter/renku/issues/866).

**Comment by olevski** [comment]
@ableuler I am not sure if you are actively working on this. I added quite a bit dummy data and could not get an error in building an image or even cloning the repo over http to another location on my computer.

This is the repo
https://dev.renku.ch/projects/tasko.olevski/large-file-test

The files I added are:
- 137 MB csv file (ALI1_dry30min.csv)
- 100 MB binary file of just nulls (test.img)
- 126 MB mp4 video file (sample_3840x2160.mp4)

I also created a similar project on renkulab.io with similar files and had no issues.

**Comment by ableuler** [comment]
Thanks for looking into this @olevski. I kind of arrived at the same conclusion a while ago, see [this comment](https://github.com/SwissDataScienceCenter/renku/issues/866#issuecomment-702055573). 

> * 137 MB csv file (ALI1_dry30min.csv)
> * 100 MB binary file of just nulls (test.img)
> * 126 MB mp4 video file (sample_3840x2160.mp4)

Those files are outside of LFS, right?

**Comment by olevski** [comment]
Yes all the files I named above are outside of LFS.

**Comment by ableuler** [comment]
Ok, thanks for verifying this systematically. Let's close this for now and re-open if/when we have another (ideally reproducible) case of the problem mentioned in the gitter thread.
