### ISSUE TITLE
build images on travis 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#169]
Our custom images used by the charts and docker-compose should be available from dockerhub (i.e. built on . The custom configs should be baked into the images and not mounted. 

- [x] jupyterhub
- [ ] notebooks service
- [x] apispec

**Comment by leafty** [comment]
Note: the charts use non-custom keycloak and gitlab. Custom images can be avoided there.

**Comment by rokroskar** [comment]
right, but I'm advocating for baking the configuration in with the image instead of copying the configuration in via templates.

**Comment by rokroskar** [comment]
@jirikuncar this won't necessarily solve the issue for dev environments using docker-compose since the image tags will use commit shas.

**Comment by jirikuncar** [comment]
@rokroskar we can also tag them with `:<branch|"latest">` name.
