### ISSUE TITLE
enable custom notebook images

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#176]
We want to be able to launch notebooks for custom environments so that users can have all the code dependencies taken care of. 

To-do: 

- [x] launch custom images based on project notebook naming scheme e.g. `<registry>/<namespace>/<project>/<env_slug>:<commit-sha>`
- [x] build images as part of the CI pipeline (#260)
- [x] add private registry credentials to pod (https://github.com/SwissDataScienceCenter/renku/issues/276)

**Comment by leafty** [comment]
Reopening as #276 is still open

**Comment by rokroskar** [comment]
closed via https://github.com/SwissDataScienceCenter/renku-notebooks/pull/21 and https://github.com/SwissDataScienceCenter/renku/pull/301
