### ISSUE TITLE
renga-only login page 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#185]
Remove gitlab from the login page. 

See here: 

https://stackoverflow.com/questions/26618030/gitlab-disable-regular-username-password-login-and-only-allow-omniauth-login

and

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/723

Trouble is that you can no longer then log in as the root user.

**Comment by ableuler** [comment]
We can create an admin user which is provided by keycloak on startup, something like
```
{
    "username": "admin",
    "email": "admin@datascience.ch",
    "name": "admin",
    "extern_uid": "admin", 
    "provider": "oauth2_generic",
    "skip_confirmation": true,
    "reset_password": true,
    "admin": true
}
```
as POST data should create an admin user which relies on the admin user present in keycloak.

**Comment by rokroskar** [comment]
this is now done in both docker-compose and helm charts
