### ISSUE TITLE
UX(search): KG-based search for entities

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#1924]
# Story

As a user, I want to be able to search over all entities (*projects*, *datasets*, *workflows*, and *users* to start) and have faceted navigation through the results.

# Vision

A more complete vision is articulated here https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/1899003951/KG-based+Search

# Design

## Search

The KG should offer an endpoint to searching for entities (projects, datasets, workflows, users/groups) and hits should consider the following fields:

- entity type
- name/title
- namespace (group/subgroup)
- user/author (the user that created the entity)
- keyword/tag
- description
- readme

By default, search should match all of the above fields.

The results should be sortable in the following ways:

- By match score (lucene text-matching score)
- By entity name (project name, dataset name, etc.)
- By entity creation date
- By entity modify date

The results should be filterable in the following ways:

- By entity type
- By owner
- By group
- By matching field (e.g., title, keyword, description, etc.)
- By visibility (restricted vs. public)
- By project template (python, R, Julia, etc)
- Creation date
- Modify date

## User

The KG should also offer an endpoint to return entities that are connected to the logged-in user. This list should contain:
- all projects that the user is a member of
- all datasets that the user has created, modified, or used
- all workflows that the user created or has used

The results should be sorted in the following way (The exact sorting needs the thought about a bit more):
- Projects where the user is a developer or maintainer that have recent commits should appear first
- Datasets where the user is an owner or maintainer that have recently been used in pipelines should appear first
- Workflows -- ?

# Missing features

- UI page for users
- KG Indexing of project tags, description, readme, and project template
- Standardized naming for conceptually equivalent fields (dataset keyword / project tag)
- Umbrella dataset result (see below)

## Umbrella dataset result

If a dataset has 3 versions and is used in 20 projects, the UI should not show 20 results for that dataset. There should be just 1 result that is shown as having 3 versions and being used in 20 projects. Only when the user navigates to the dataset details view do we expand it to show the different versions and the projects it is being used in.

# Questions

What happens to projects that are not in the KG? It is not an expected situation, but there could happen due to a bug, and users need some way to workaround and fix.

# Mock Up

![image](https://user-images.githubusercontent.com/1196411/124917702-6dacfd80-dff4-11eb-8f43-100f45da4ffb.png)

# Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation

**Comment by ableuler** [comment]
> The purpose of the Renku score is to increase the visibility of active, interesting projects. It should consider the following properties

We could also factor in the presence of renku-specific things like datasets and workflows in the project.
