### ISSUE TITLE
Get private token from GitLab as part of acceptance tests

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1927]
Currently, the acceptance test user must have the same username and password registered in both keycloak and gitlab. this is necessary for pushing/pulling from/to GitLab. As part of the browser based tests we could get a private token from GitLab and use that for push/pull instead.

**Comment by jachro** [comment]
This has been done so now the tests obtain an OAuth access token from GitLab. So no need to specify/match the GitLab credentials in the tests anymore.
