### ISSUE TITLE
GitLab API in Acceptance tests

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku#1970]
*Current Situation*
The acceptance tests need to click around the GitLab UI. Although it is relatively static, it is still potentially fragile and slow to use the GitLab UI in acceptance tests.

*Solution*
 It would be much faster, reliable, and simpler to use the API. However, we need to get an access token for each test user and put it in the config file. This is simple in the case of local development. However, we need to decide how we want to store this secret for use with the helm tests in various environments. 

*Describe the solution you'd like*
- [ ] obtain an OAuth2 GitLab token in a completely automated way, offering the credentials: https://docs.gitlab.com/ee/api/oauth2.html#resource-owner-password-credentials-flow.
- [ ] Once the tests got the OAuth2 token they should be able to use it to call any other GitLab APIs.
- [ ] delete the token later or set an expiration date,
- [ ] Add facility to call GitLab API from the test helpers 

**Describe alternatives you've considered**
1. Store Secret in some secrets variable 
Read the secret from the variable 
Add functionality to read the value from a config file 
1. Continue to use the GitLab API. It's quite difficult to get the CSS selectors correct. The pages load slowly as well. It takes time to debug.

**Comment by travissarles** [comment]
@jachro @pameladelgado @aledegano please add more specs or clarifications to this issue as you see fit.

**Comment by aledegano** [comment]
It should be possible to obtain an OAuth2 GitLab token in a completely automated way, offering the credentials: https://docs.gitlab.com/ee/api/oauth2.html#resource-owner-password-credentials-flow.
Once the tests got the OAuth2 token they should be able to use it to call any other GitLab APIs.

Do you think that would work?

**Comment by pameladelgado** [comment]
I think we definitely should use directly the GitLab API in our acceptance-tests.
Generating a token in an automated way like @aledegano pointed out should work but we'd have to be careful to delete the token later or set an expiration date, otherwise we'd end up with potentially thousands of tokens for our CI/CD. This should also be possible to do in an automated way afaik.

**Comment by jachro** [comment]
Great idea! I'm on the QA rota next sprint so looking forward to try that out!
