### ISSUE TITLE
Unable to get local issuer certificate in renku gateway

### ISSUE THREAD

**Issue by Abdellah91** [SwissDataScienceCenter/renku#1971]
Hello,
**Describe the bug**

I try to install renku on kubernetes cluster using renku Helm chart
and I'm getting this error: "Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition"
**when I list pods deployed** 
   - I get few pods(renku-post-install-keycloaks-xxxx) with error Status 
   - renku-gateway-auth-xyzewxxxx with CrashLoopBackOff status
**logs of pods `renku-post-install-keycloaks-xxxx:**
  Could not get a token. Is Keycloak running under https://renku_url/auth/?
  Getting an admin access token for Keycloak...Keycloak not responding, retrying in 10 seconds...
  Getting an admin access token for Keycloak...Keycloak not responding, retrying in 10 seconds...
**logs of pod renku-gateway-auth-xyzewxxxx:**
  INFO in __init__: Obtaining public key from https://renku_url/auth/realms/Renku
   ERROR in app: Exception on /health [GET]
  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='renku_url.com', port=443): Max retries exceeded 
  with url: /auth/realms/Renku (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] 
  certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

**To Reproduce**
in a terminal with configured kubectl
helm upgrade renku renku/renku --namespace renku -f renku-values.yaml --timeout 1800s --debug

**Expected behavior**
All pods on running or completed status 

**Run environment (please complete the following information):**
 - local terminal 
- renku-python version: python3.7
- kubernetes deployed on ubuntu 18.04 VMs

Thanks

**Comment by pameladelgado** [comment]
Hello @Abdellah91 
I see that you closed the issue, have you figured out the problem?
If not, from what you describe, it looks like you dont have a valid certificate for your domain.

In the future please don't hesitate to post related questions on our dedicated admin category in our [discourse forum](https://renku.discourse.group/c/renku-admin/12).

**Comment by Abdellah91** [comment]
Hello,
Thank you for your answer. You are right I had issue with my certificat but now this issue is resolved :)

Thanks
