### ISSUE TITLE
Automatically deploy to staging on tag

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#1977]
Whenever we tag a release or a release candidate, the tagged version should be deployed automatically on a staging deployment which runs against the production gitlab instance.

**Comment by pameladelgado** [comment]
we can use the existing `staging` dev deployment, we need to:
- move the namespace to Renku project on rancher
- extract, encrypt and save its values on the ops-dev repo
- same for PVs, PVCs
- automate the deployment on a CD pipeline, including running the acceptance tests
- ideally I would also make an upgrade to an rc/official release after a tag has been made and the charts are available (to verify the charts are properly built)

**Comment by ableuler** [comment]
> * ideally I would also make an upgrade to an rc/official release after a tag has been made and the charts are available (to verify the charts are properly built)

Not sure I understand what you mean here. I would expect every tag to be deployed on this staging environment only after the tag has been made and the corresponding chart has been published. Did you have something else in mind?
