### ISSUE TITLE
instructions on how to reproduce renkulab environment locally

### ISSUE THREAD

**Issue by schymans** [SwissDataScienceCenter/renku#2040]
As discussed in https://renku.discourse.group/t/installation-instructions-incomplete/208, it would be good to have an easy way to re-build locally an adequate environment for a renkulab project. The packages listed in requirements.txt are installed on top of the standard installation, but it is not obvious how to reproduce the standard installation locally. If the information contained in the dockervile, environment.yml and requirements.txt is sufficient to achieve this, could some instructions be added to the docu how to use them?

**Comment by rokroskar** [comment]
This is also related to https://github.com/SwissDataScienceCenter/renku/issues/836

**Comment by rokroskar** [comment]
@schymans #2043 adds docs for this - you can find the preview [here](https://renku.readthedocs.io/en/2040-local-interactive-session/user/interactive-running-locally.html) - could you take it for a spin and let me know in the PR comments if something isn't clear or not working?

**Comment by schymans** [comment]
This is great, thank you, @rokroskar! I just tried it, but get an access forbidden: 
```
$ sudo docker pull registry.renkulab.io/gitlab/ba_math_gen-16/et-data:e0796781
[sudo] password for user1: 
Error response from daemon: Get https://registry.renkulab.io/v2/gitlab/ba_math_gen-16/et-data/manifests/e0796781: denied: access forbidden
```
Did I misunderstand or do I need to create a second key for docker? I can push to this repo using git with no problems. Perhaps a full example of pulling and running the docker container would be helpful in the docs. Would save a lot of time to people that don't use docker regularly.
