### ISSUE TITLE
Docker-compose trying to pull non-existant tag for jupyterhub

### ISSUE THREAD

**Issue by 3C111** [SwissDataScienceCenter/renku#206]
Command "PLATFORM_VERSION=development docker-compose pull"
 
Results in 
"Pulling singleuser (rengahub/singleuser:development)...
ERROR: manifest for rengahub/singleuser:development not found"

After which pull does not continue.

**Comment by 3C111** [comment]
So when is that :]

**Comment by rokroskar** [comment]
Two things here: 1) `singleuser` needs to be removed from the `docker-compose.yml` and 2) the `singleuser` image is built in the `Makefile`, e.g. you can do `make tag` to build the custom images we use.

**Comment by rokroskar** [comment]
@3C111 I'm not sure this is really a problem? If not, could you please close the issue?

**Comment by 3C111** [comment]
@rokroskar why would this not qualify as an issue for you?

**Comment by rokroskar** [comment]
@3C111 because the image is built when you do `make start`
