### ISSUE TITLE
refactor charts to use dependencies when possible

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#208]
In addition, do not modify the gitlab database directly where it is not necessary, e.g. for application configuration options, you can use the REST API (see #187).

- [x] postgres (#293)
- [x] keycloak (https://github.com/SwissDataScienceCenter/renku/pull/336)
- [x] redis (#337)

~~We should include the gitlab configuration in the image, which should allow us to use the stock gitlab chart as a helm dependency directly.~~ 

~~instead, use an omnibus [gitlab chart](https://docs.gitlab.com/ee/install/kubernetes/gitlab_omnibus.html)?~~ the omnibus chart leaves a lot to be desired, see comments below.

**Comment by leafty** [comment]
https://gitlab.com/charts/gitlab-omnibus chart does not integrate with existing ingress, so I would wait until the native cloud one is in a usable form.

**Comment by rokroskar** [comment]
@leafty makes sense -- though I think this issue can be closed as I don't think we use init containers anywhere anymore?

**Comment by leafty** [comment]
I was thinking we could rephrase it a bit...
I think we can use the same idea to make postgresql a chart dependency, with a job doing the database init.

**Comment by rokroskar** [comment]
yes, exactly. We can keep this open and increase the scope. I guess postgres is the biggest one because of the the db init steps. Redis can easily be a dependency. Once we write the renku realm as REST calls, then keycloak can also follow.

**Comment by rokroskar** [comment]
closed by #337
