### ISSUE TITLE
charts: upgrade GitLab and Postgresql version

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#2105]
To be able to use GitLab versions newer than `12.9` we need to upgrade the Postgresql version used in Renku to `11.9`.
This is also related (but not entirely necessary) to migrating production environments to GitLab cloud native charts #2093

**Comment by ableuler** [comment]
Partially resolved in #2117 .

**Comment by pameladelgado** [comment]
FYI for upgrading GitLab to `13` we need to add an extension on Postgresql. This line change should be enough: https://github.com/SwissDataScienceCenter/renku/blob/upgrade-postgresql/helm-chart/renku/templates/configmap.yaml#L109
