### ISSUE TITLE
investigate using GitLab's email notifications

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#2109]
We need to enable some sort of notifications in GitLab instances that are attached to our standard Renku deployments. The first and maybe easiest is to simply enable the email notifications. 

To determine:

* to what extent can we modify the emails? 
* is it possible to give them a renku/renkulab look and feel? Can we add a log etc.? 
* If there are gitlab-specific branding elements (logos, headers, footers) can we change those any way we want? 

This should be a 1-2 days max spike after which we can determine what course of action we'd like to take.

**Comment by rokroskar** [comment]
Relevant gitlab docs: https://docs.gitlab.com/omnibus/settings/smtp.html

**Comment by rokroskar** [comment]
Enabing emails with a few modifications results in the following:

adding a footer (the colors can obviously be changed):

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3353586/119910604-cb5f1c00-bf57-11eb-910a-3e3e2fcebb79.png">


This text also appears at the bottom of standard emails about project activity, e.g. issues comments:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3353586/119910689-f77a9d00-bf57-11eb-966a-240296d45f7c.png">

Emails about password resets etc look like this:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/3353586/119911936-ad46eb00-bf5a-11eb-94d6-12da41a5f6b7.png">

**Comment by rokroskar** [comment]
@SwissDataScienceCenter/renku-ui-maintainers would be good to get your opinion on the email modifications - until the new UI rollout is ready, we would use the old SDSC logos of course.

**Comment by ciyer** [comment]
I think we can start using the new colors here already. No point in introducing the old color palette just to change it in one month.

> <img alt="image" width="774" src="https://user-images.githubusercontent.com/3353586/119911936-ad46eb00-bf5a-11eb-94d6-12da41a5f6b7.png">

The background on the logo is white. I would make it transparent, so it looks better against the light gray.

**Comment by rokroskar** [comment]
Do you mean using the new colors or the new logo? 

I agree about the background - do we have versions with transparent backgrounds?

**Comment by rokroskar** [comment]
This is one annoying "feature" - because the sign in is actually from the gateway, we get emails like this

![image](https://user-images.githubusercontent.com/3353586/119944771-f87def80-bf94-11eb-8325-68911e98b652.png)

I haven't figured out yet how to turn this off, but it's bound to be confusing. Not sure if it's enough to not start using email notifications though.

**Comment by ciyer** [comment]
> Do you mean using the new colors or the new logo?

 I meant the logos.

> I agree about the background - do we have versions with transparent backgrounds?

I see that the logo w/ transparent background has been deployed. It looks much better.

Did any of the changes you made cause this footer to be introduced?

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1196411/119981471-f67c5680-bfbd-11eb-8128-bb0c898a5756.png">

**Comment by rokroskar** [comment]
yes exactly - the footer I also added, the same text is used in the email footer. I would love to fix the link colors, I just used markdown here so it's the default link color.

**Comment by rokroskar** [comment]
@ciyer the setting doesn't allow much freedom, but I suppose we could add an html tag in there to specify the link colors:

![image](https://user-images.githubusercontent.com/3353586/119982388-106a6900-bfbf-11eb-95c9-cbd0d401ffe2.png)

**Comment by rokroskar** [comment]
For reference, the colors used for the footer are:

bg: #F5F5F5 
text: #01192D 
link: #296047

**Comment by rokroskar** [comment]
closing, this has been implemented and rolled out to renkulab, limited, and our dev cluster
