### ISSUE TITLE
keycloak: use API to create new clients and users

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku#214]
We should consider using REST API to create clients and users in KeyCloak db instead of templated config dump.

**Comment by ableuler** [comment]
Agree - I actually started looking into this already yesterday.

**Comment by jirikuncar** [comment]
Hopefully, we can also switch to the `incubator/keycloak` chart.

**Comment by rokroskar** [comment]
@ableuler is there a branch with your work on this somewhere already? @fgeorgatos started to work on it as well, would be a shame to duplicate efforts.

**Comment by ableuler** [comment]
No branch, what I did related related to this issue can be summarised as followed:

- I looked at how to use the admin credentials to obtain a temporarily (only 1 minute or so...) valid access token with admin privileges for keycloak which can then be used to create the actual users, clients, etc (see https://github.com/SwissDataScienceCenter/renku-demo/blob/master/steps/2-create-users.py) for an example.
- I went through the API documentation to realise that the realm itself can not be created through the API, meaning that the empty Renku realm should still be created from the template. However, this template is not going to change much (if at all) when users and clients can be added through an api.

Hope this helps, great if @fgeorgatos can move forward on this issue 👍

**Comment by leafty** [comment]
Forgot about the existence of this issue.

I believe everything can be manipulated by the API, the thing is that the API itself is not documented (while all the actions from the admin console are well described).

Scripting the API calls can be made in bash with the use of the keycloak admin cli. I tried a few examples with @3C111 which you can find here: https://github.com/SwissDataScienceCenter/incubator-kc-abac

**Comment by fgeorgatos** [comment]
ugh, perhaps it should be me perhaps the person being asked at, but: 
* what is the status on this issue?
(somehow, when #268 was closed, it fall completely out of my view)

**Comment by rokroskar** [comment]
status is "open" :)
