### ISSUE TITLE
Flaky `MergeRequestsAndIssuesSpec` test scenario

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#2244]
The merge requests and test scenario has been failing frequently recently, see for example [this ci pipeline](https://github.com/SwissDataScienceCenter/renku/runs/3360887987). It seems like the `test-branch` hasn't been created and thus no merge request can be created.

**Comment by jachro** [comment]
I checked this spec and it looks it has changed significantly since UI switched to IFrames for both issues and merge requests. Hence, no real PR creation is happening now. I also run the spec few times and it looks like it passes consistently. Closing it for now.
