### ISSUE TITLE
Enable propagation of custom root CA certificate through chart

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#2281]
Running RenkuLab with a TLS certificate that is issued by a custom CA is currently a very painful process. See [this blogpost](https://renku.discourse.group/t/feedback-on-offline-deployment-with-custom-root-ca/299) for a taste. While an approach based on `kustomize` would seem reasonable for automating all the steps described in the post, there is the mentioned issue with helm-hook resources not being considered part of the helm release and thus not getting modified by the post-rendering step. On top of that, renku-graph has already implemented the option to pass-in a custom root CA certificate through the helm chart, so doing it all through the charts instead seems cleanest to me. 

Specifically, the task will be to define a configmap that holds some additional root certificate(s) which are provided through the renku global values and then mount it into each container which communicates with other Renku services through their public URL. Also, the respective client doing the requests will have to be pointed to the mounted certificate, usually by providing a given env variable. 

This will require many PRs in many of the Renku component repos, in this epic we can keep track of them. This is a potentially incomplete list of known places which need modification:

- gateway (traefik/Go client)
- gateway auth (python client)
- KG (chart and image changes already implemented, potentially some alignment with renku chart changes needed)
- renku-notebooks (python client)
- git-clone (git client, add configuration to .git/config that we're already setting up there)
- keycloak init realm script (python client)
- core-service (git client, probably some global, non-repo specific not 100% sure which container. As git uses curl, just setting SSL_CERT_FILE might actually be enough here too.)
- ui-server (not yet live, but better so sync already)

On top of that I'm unsure about:
- Keycloak (java client, would likely require building a custom keycloak image trough chartpress). I am not sure though, but it seems to me that Keylcoak only ever acts as https client if it uses an upstream ID provider.
- (Components of) GitLab as  clients (calling the KG webhook, Keycloak as oAuth provider or other parts of GitLab) 

Finally, it would be awesome if we include this setup in our test suite. Otherwise it's only a matter of time until someone will accidentally add features which break such a setup.

**Comment by MichaelAML** [comment]
At the moment, we need to extend the following Helm Charts/Docker images with a global root CA certificate (list without guarantee on completeness):

https://github.com/SwissDataScienceCenter/renku
https://github.com/SwissDataScienceCenter/renku-gateway
https://github.com/SwissDataScienceCenter/renku-graph/tree/master/knowledge-graph
https://github.com/SwissDataScienceCenter/renku-graph/tree/master/webhook-service
https://github.com/SwissDataScienceCenter/renku-notebooks
https://github.com/SwissDataScienceCenter/renku-notebooks/tree/master/git-clone
https://github.com/SwissDataScienceCenter/renku-python
https://github.com/SwissDataScienceCenter/renkulab-docker

Hence, in the future it should be possible to configure this from a single point of truth.

**Comment by pameladelgado** [comment]
> Hence, in the future it should be possible to configure this from a single point of truth.

We already use a global renku variable in our charts for supporting this on renku-graph, the plan is to use the same variable, when provided, everywhere else.

The path to specify this is `global.clientCertificate.value` in the main renku values file.
 
Renku graph reference: [issue #43](https://github.com/SwissDataScienceCenter/renku-graph/issues/432) closed by [509](https://github.com/SwissDataScienceCenter/renku-graph/pull/509)
