### ISSUE TITLE
contributor license agreement link not working

### ISSUE THREAD

**Issue by sebastianbertoli** [SwissDataScienceCenter/renku#2347]
**Describe the bug**
contributor license agreement link not working and I cannot find the document in the repo. 😬 

**Link to project**
https://github.com/SwissDataScienceCenter/renku/blob/53a9e6f89cb080bc97f2daf1608e53a35c52b48e/CONTRIBUTING.rst

**Comment by rokroskar** [comment]
Thanks @sebastianbertoli - you're right, it appears the the CLA is stored in a private repository for some reason 🤦 

I've moved the wiki page here: https://github.com/SwissDataScienceCenter/renku/wiki/Legal and I will update the `CONTRIBUTING` doc. Thanks for pointing it out!
