### ISSUE TITLE
Acceptance tests failing on dataset search

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#2355]
Acceptance tests frequently fail at the free text dataset search with what looks a bit like an API exception, for example [here](https://github.com/SwissDataScienceCenter/renku/runs/3299900521). To me this could be a problem of the graph service rather than of the tests themselves.

![image](https://user-images.githubusercontent.com/13014091/130058915-f02e5789-9f11-4d13-8a45-fb20a9df2200.png)

**Comment by jachro** [comment]
This bug was addressed in https://github.com/SwissDataScienceCenter/renku/pull/2264. Please feel free to re-open the issue if you'll notice the `EOF` happening again.
