### ISSUE TITLE
Select branch in renku.ini when starting a session

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku#2380]
**Is your feature request related to a problem? Please describe.**
I use renkulab to share a streamlit app with a collaborator who then creates and manipulates files with the help of the app. I'd like this to be done on another branch than the master.

**Describe the solution you'd like**
Allow to select the branch to start a session from in renku.ini.
(Or some other approach that you find is suitable.)

**Describe alternatives you've considered**
So far, the branch needs to be manually adjusted. This often slips my or my collaborator's mind and we then end up starting the session in the master branch.

**Additional context**

**Comment by ciyer** [comment]
This request makes sense and should be easy to implement. The only issue I see with it, though, is that *all* sessions will be started on this branch, regardless of whether the user is trying to access the streamlit app or something else. 

I'm assuming there is a reason you do not want to merge this branch to master, but, as an alternative, have you thought of forking the repo and using the fork for running the streamlit app? There, the app could be on the primary branch, and, if you made changes that needed to go back into the main repo, it would be easy to create a PR to merge them.

**Comment by rokroskar** [comment]
No longer relevant in Renku 2.0
