### ISSUE TITLE
reduce the size of images

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#239]
the `renku` notebook images are based on the `jupyter` docker stacks and seem quite large. E.g. 

```
docker images --filter "reference=renku/singleuser*"
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
renku/singleuser    285198f23f0c        776527be099c        9 hours ago         2.8GB
```

This is based on the `jupyter/minimal-notebook` image, which itself is about the same size. Could we use a different base image to reduce the image size?

**Comment by 3C111** [comment]
We could use the jupyter/base-notebook. It is much smaller, but misses 

> Pandoc and TeX Live for notebook document conversion
> git, emacs, jed, vim, and unzip

However, is this all really needed? We could add git to the Dockerfile and still have a smaller image than the minimal-notebook.

**Comment by leafty** [comment]
Pandoc and texlive are used for download as pdf option. I think it's ok to remove these system packages.
