### ISSUE TITLE
Remove or make optional demo user as gitlab admin

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#242]
User `demo` should not be a gitlab admin:
https://github.com/SwissDataScienceCenter/renku/blob/4d4d1c888e8b64b3635a35b21a447ba8fb0211ba/charts/renku/templates/configmap.yaml#L42-L43

**Comment by ableuler** [comment]
Totally agree - there's even an open PR for this: https://github.com/SwissDataScienceCenter/renku/pull/212 There's only the helm part missing for the PR to be merged. @leafty Feel free to complete this, shouldn't take long...

**Comment by leafty** [comment]
Also noticed that `dummy-secret` is an admin token!!!

**Comment by rokroskar** [comment]
@leafty the default secrets are not secret by default... ;)

what we do need (soon) is documentation outlining exactly which of these secrets someone who wants an internet-facing deployment needs to take care of.

**Comment by leafty** [comment]
For me, we should:
- Leave the secret unset in `values.yaml` so that the chart fails when passwords/secrets are not set. We can fill with dummy values in `minikube-values.yaml`.
- Avoid using `randAlphaNum` or other pre-filled random strings. Unless we can update the components to take this into account, this would lead to configuration mismatch.
