### ISSUE TITLE
Version service

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku#2422]
The goal is to get information about the version of each service. Some services may have additional data (e.g. renku core actually deploy more than one version per time)

We need the following components:
- [ ] `GET /version` endpoints for each service. We will start with the services we develop and expose (core, gateway, kg, notebooks, ui, ui-server)
- [ ] An aggregator service that will collect the versions of each service. It will periodically ping the services (this means the version data won't be updated realtime). The relevant services should be marked as `discoverable`, probably with some metadata attached to the pods (or otherwise conveniently available at k8s level).

The service will expose a `GET /version` endpoint with the collected data. It would be nice to also include the renkulab version.

Detailed issues will be opened separately, this is the umbrella epic that collects generic information and keeps track of the progress until we have a running prototype.

Here are the slides used in the short presentation: [Slides versions endpoints 2022-01-22](https://github.com/SwissDataScienceCenter/renku/files/7906486/_versions.endpoints.pdf)

**Comment by rokroskar** [comment]
I believe this has been finished.
