### ISSUE TITLE
Show all running sessions from forks

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku#2449]
This is the result of a request:

> We had an interesting request from a renku project - they were wondering if it would be possible to see all the running sessions related to a project. The specific use-case is that for someone doing a workshop using renkulab, it’s impossible for them to know how many sessions the participants have started. I figured this is interesting info also in the more general case of just being an owner of a public project and seeing the sessions that are active which use it. It would be relatively easy to return this information from the notebooks service about sessions from a specific project, but how could we handle forks? The typical workflow is still that participants in trainings fork the source repo and work from there, so we would need to be able to recognize the forks.

**Comment by olevski** [comment]
https://github.com/SwissDataScienceCenter/renku-notebooks/issues/910 should also be part of this epic.

**Comment by rokroskar** [comment]
We should perhaps revisit this separately in Renku 2.0 as part of the features around teaching. cc @lokijuhy
