### ISSUE TITLE
Tutorial Data Link returns 404 error

### ISSUE THREAD

**Issue by wesjdj** [SwissDataScienceCenter/renku#2522]
**Describe the bug**
The link to the [Flights tutorial](https://renku.readthedocs.io/en/latest/tutorials/first_steps/03_add_data.html) data returns a 404 at the following URL: https://www.doi.org/https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/WTZS4K

**Link to project**
https://renku.readthedocs.io/en/latest/tutorials/first_steps/03_add_data.html

**To Reproduce**
1. Go to https://renku.readthedocs.io/en/latest/tutorials/first_steps/03_add_data.html
2. Click on The DOI for the dataset we want to import is [https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/WTZS4K](https://www.doi.org/https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/WTZS4K).

**Expected behavior**
An option to download the zip file containing the data used in the rest of the tutorial

**Screenshots and/or execution output**
![Screenshot 2022-03-22 at 10 29 41](https://user-images.githubusercontent.com/515042/159449511-aea7314f-8409-4ebc-8c18-9348045705a1.png)

**Run environment (please complete the following information):**
 - Firefox

**Additional context**
Removing the `https://www.doi.org/` prefix of the URL redirects to a page where the zip can be downloaded.

**Comment by rokroskar** [comment]
uh oh how did that happen - the URL should be https://doi.org/10.7910/DVN/WTZS4K
