### ISSUE TITLE
Replace usage of apt-get inside the postgres container in configmap

### ISSUE THREAD

**Issue by shock0572** [SwissDataScienceCenter/renku#2523]
The configmap for Renku helm chart is currently using apt-get inside a container:

https://github.com/SwissDataScienceCenter/renku/blob/8e0e9aae65c4af9d28203eeef0c1960292aee01f/helm-chart/renku/templates/configmap.yaml#L18-L19

This works in non-constrained, non-proxied environments for deployment, but fails anywhere else.
Those lines should be removed and a new container should be used in 

https://github.com/SwissDataScienceCenter/renku/blob/8e0e9aae65c4af9d28203eeef0c1960292aee01f/helm-chart/renku/templates/post-install-job-gitlab.yaml#L26

by choosing a proper container like:
https://hub.docker.com/r/stangirard/alpine-powerhouse
https://hub.docker.com/r/arunvelsriram/utils
that already includes all the needed tools by the post-install-gitlab, or build a renku/utils container in house.
The solution above has been tested and used in our current deployment.

**Comment by rokroskar** [comment]
I agree this is very bad practice and should be changed :) btw, maybe update the description to link to current code, e.g. https://github.com/SwissDataScienceCenter/renku/blob/8e0e9aae65c4af9d28203eeef0c1960292aee01f/helm-chart/renku/templates/configmap.yaml#L18-L19

**Comment by rokroskar** [comment]
done in #2563
