### ISSUE TITLE
Starting session fails on git-clone init container

### ISSUE THREAD

**Issue by mfranzon** [SwissDataScienceCenter/renku#2537]
I have deployed renku using helm in an on prem cluster. All the components seems to work fine, the only problem that I am facing out is that when I am trying to launch a new session, using a custom image, made from a notebook template, the git-clone container is not able to clone the repo. 
It complains that :
` No git repo found, setting up repo and cloning into https://<domain>/gitlab`

I think that it should use `https://<domain>/gitlab/path/to/.git` to clone the repo in which I have the template or I am missing something ?

My renku chart version is the 0.12.3

Thank you very much for your help and for developing this great project.

**Comment by rokroskar** [comment]
Hi @mfranzon apologies for seeing this late - that message is not an error, it simply states that the repo has not been cloned yet in this volume (though I agree the URL there is incorrect... should be the repository URL). Can you show the rest of the init container's logs?

**Comment by mfranzon** [comment]
Hi @rokroskar , thank you for your reply. 
At the moment I can see just two containers running, one is the init-certificates, the other the git-clone.

The logs from crictl logs commands of init-certificates is:

`2022-04-01T09:19:12.792268690Z Purging old certificates`
`2022-04-01T09:19:12.793858655Z Updating certificates`
`2022-04-01T09:19:12.837545964Z WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping`
`2022-04-01T09:19:12.913646708Z De-reference symlinks`

The git-clone container : 

`No git repo found, setting up repo and cloning into https://<domain>/gitlab`

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

```

**Comment by mfranzon** [comment]
Just to mention, another interesting aspect is the following:
if I make an` env | grep git` into the container I got :
```
GIT_URL=https://<domain>/gitlab
REPOSITORY_URL=https://<domain>/gitlab/test/test2.git
```
The repository_url variable contains the correct path to the git folder but git_url not. I hope this could be helpful.

**Comment by rokroskar** [comment]
Are you able to clone the repo locally? e.g. running `git clone https://<domain>/gitlab/test/test2.git` in your terminal?

**Comment by mfranzon** [comment]
Yes, I can clone it

**Comment by rokroskar** [comment]
the fact that the init container is still running means its timing out probably on the connection - can you log in to the container and clone it there?

**Comment by mfranzon** [comment]
I cannot clone the repo into the container for permission issues :
`fatal: could not create work tree dir 'test2': Permission denied`
But I have noticed that if I make a `curl`, for example, it remains hanging...

**Comment by rokroskar** [comment]
Can you reach gitlab at all from inside the cluster? It definitely seems like a network problem to me.

**Comment by olevski** [comment]
@mfranzon when you log into the container (the `jupyter-server` one) can you try to just create a folder or a random file. To me that message you posted (`fatal: could not create work tree dir 'test2': Permission denied`) seems like the user that is running the session does not have permissions to create the files for the repository. So can you try to just to `mkdir test-folder` or `touch test-file` in the container and see if that works?

**Comment by olevski** [comment]
And one more thing is when you run a curl command from within the `git-clone` container can you add the `-v` command and see what you get and share it here? It could be that the connection to your gitlab instance is being blocked somehow. Or there could a certificate issue.

You deployed the gitlab instance that comes included in Renku? Or you are using a standalone one?

**Comment by mfranzon** [comment]
Thank you for these good points. 
@rokroskar yes, I can reach gitlab from any other container in the cluster.

@olevski , I can create files into `/work` folders and when I run` curl -v ` I got:
`*   Trying <ip>:443...`

I use the gitlab instance included in Renku.

I have also another question, where can I find the yaml  file that is used to deploy the new pod when I start a new session ? Or it is created in another way ? Thank you

**Comment by rokroskar** [comment]
Could you try redeploying and set this value:

```
notebooks.amalthea.networkPolicies.enabled=false
```

It turns off the network policy that is configured for the notebook session pods. It might be that something funny is happening there.

**Comment by mfranzon** [comment]
Yes sure, I will have a try and let you know in a while! Thank you

**Comment by rokroskar** [comment]
one more thing to check - which IP does the gitlab URL resolve to? If it's an internal IP we block it to prevent access to other services from user sessions.

**Comment by mfranzon** [comment]
Good point, the IP is internal, you cannot reach if you are not into the private network.

**Comment by mfranzon** [comment]
Thank you @rokroskar  and @olevski for your support.
 Setting `notebooks.amalthea.networkPolicies.enabled=false` solve the problem.
