### ISSUE TITLE
Swagger page does not fully work

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku#2569]
The following happens on a fresh Renku install:
- delete all the gateway and redis pods (to clear any temporary state that gateway/redis may have for user sessions)
- visit the swagger page
- log in with the PKCE flow
- doing a request through swagger fails with a 500 error

A workaround for this is to visit the renku page and manually log in. Then something in the gateway or somewhere happens that fully completes the auth flow and after that sending requests through swagger works.

So this could be a problem in the swagger setup or in the ui or in the gateway.

**Comment by rokroskar** [comment]
Unclear if this is still an issue with the gateway refactoring. Will close for the time being.
