### ISSUE TITLE
[helm] Consider using yaml anchors, references and merge keys in `values.yaml`

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#258]
YAML allows you to not repeat yourself by using anchors and references or merge keys.

--> This would allows to streamline the `values.yaml` file by avoiding repetition and by making the `global` section smaller.

*Note:* I tried using it with helm 2.9 and it picked it.

**Comment by leafty** [comment]
Also this would make chart dependencies configs easier.

**Comment by ableuler** [comment]
We are using anchors now for some of our deployment-specific values files. I'm closing this issue in favour of #638.
