### ISSUE TITLE
[notebooks] spawners should handle LFS objects

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#259]
Using the `renku-demo` script and actually running the notebook gives this: 

![image](https://user-images.githubusercontent.com/3353586/40847358-70479e34-65bc-11e8-9cce-fe813b533803.png)

**Comment by leafty** [comment]
I guess alpine/guy doesn't come with LFS...

**Comment by erbou** [comment]
Reopen because same issue for the k8s spawner, can reproduce with weather-zh project on testing.datascience.ch.
