### ISSUE TITLE
check image build status

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#263]
Once we have image builds working (contingent upon #260 and #246) we will want some way of letting the user know when the image build is completed. This could happen:

1) in the UI somewhere next to/near the "Launch notebook" button
2) in the notebook service (if image isn't in the registry, redirect to a "waiting for the image" page)
3) check the job status in the `SpawnerMixin`

cc @ciyer @jirikuncar @leafty @ableuler

**Comment by leafty** [comment]
This can be a waiting page from the `Launch` button, similar to binderhub.

**Comment by rokroskar** [comment]
Yes exactly. In addition there could be something indicating the status of the build in the ui.

**Comment by leafty** [comment]
For ui implementation, 2 steps required on the gitlab api:
- hit `GET /projects/:id/repository/commits/:sha`: https://docs.gitlab.com/ce/api/commits.html#get-a-single-commit
- hit `GET /projects/:id/pipelines/:pipeline_id`: https://docs.gitlab.com/ce/api/pipelines.html#get-a-single-pipeline

**Comment by rokroskar** [comment]
actually for this you just care about the image build so you want to look at 

`GET /projects/:id/jobs/` and filter on commit ID and the stage name (at this point it's `image_build`)

**Comment by leafty** [comment]
true :)
but then you have to handle pagination
