### ISSUE TITLE
Tutorial ideas

### ISSUE THREAD

**Issue by aplamada** [SwissDataScienceCenter/renku#2636]
By following the tutorials I learned a lot. It is a very good source for newcomers.  

I have some random ideas that I think might be useful to share:
- Stopping the session or deleting the project is not part of the tutorial (I managed to do them),
- Subsection `Create a new project`: the UI is slightly different. The role of the template can be emphasised better for Python / R / Julia (the target audience of the tutorial) by using the new UI.
- Subsection `Start a session -> Adding data from the local file system`: this is very important in practice but it is not really used in the tutorial. It can be either used later in the tutorial by updating the dataset, or it might be relocated to the `How-to Guides`
- Subsection `Ways to do data science in Renku`: one has to rename the notebook, but it is not clearly mentioned the new name `notebook.ipynb`. Also `renku save` it seems to commit also all untracked files, so it could help to mention this explicitly and to do a `git status` before
- Subsection `Interactively explore the flights data`: it might help to show a figure with the steps needed to download a file
- Subsection `Building scripts`: it is written where to upload the script, but a figure might help. Moreover it might to run the script before using the `renku run` since this is closer to the trial and error approach that I apply in practice

Thanks for all the effort!

**Comment by rokroskar** [comment]
The tutorials are changing entirely for Renku 2.0. Closing this for now.
