### ISSUE TITLE
launched notebook in Init:CrashLoopBackoff

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#265]
The notebook server launched by the k8s spawner can get stuck in `Init:CrashLoopBackoff`.

From the init container logs:
```bash
fatal: destination path '/repo' already exists and is not an empty directory.
```

Possible fix is to run `rm -rf` beforehand:

https://github.com/SwissDataScienceCenter/renku/blob/01692c9cfca62ed7df7da2679e5910bb6f4892a2/services/jupyterhub/spawners.py#L192

https://github.com/SwissDataScienceCenter/renku/blob/01692c9cfca62ed7df7da2679e5910bb6f4892a2/services/jupyterhub/spawners.py#L290

**Comment by rokroskar** [comment]
Hm this was a problem a long time ago and should've been fixed already. Is there a particular situation that causes it?

**Comment by leafty** [comment]
One easy way to reproduce it: cycle minikube stop/start with a reunning nb server.
