### ISSUE TITLE
Run cypress acceptance tests

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku#2700]
The basic cypress tests from here: https://www.npmjs.com/package/@renku/notebooks-cypress-tests

Should run as another set of acceptance tests. This will allow us to test our rstudio sessions. Which we currently do not do at all in our existing acceptance tests.

In addition we should run said acceptance tests for both anonymous and registered users. I believe we currently do not do this either in our acceptance tests.

**Comment by lorenzo-cavazzi** [comment]
Cypress acceptance tests now run together with the Selenium tests
