### ISSUE TITLE
Cannot connect to https://renkulab.io/ with GitHub after manual account creation

### ISSUE THREAD

**Issue by oleg-nenashev** [SwissDataScienceCenter/renku#2867]
**Describe the bug**
I manually created an account from my phone, and now to connect using the GitHub OAuth. Unfortunately it does not work, because the service cannot send an email when I agree to proceed to the existing account. Error message: "Failed to send email, please try again later."

**Link to project**
N/A. Account is associated with my public email, see the profile of @oleg-nenashev

**To Reproduce**
1. Create a new account using the email/password option
2. Try to connect the service using GitHub OAuth
3. Agree with continuing to existing account

**Expected behavior**

Accounts are merged, login is successful

**Screenshots and/or execution output**

See the screenshot below. The behavior continue when a new log-in attempt is made.

![image](https://user-images.githubusercontent.com/3000480/208466412-0220aeaa-8896-41d7-8da6-c6ad2a39e623.png)

**Run environment (please complete the following information):**
 - Chrome latest

**Additional context**
Status on https://renkulab.statuspage.io/ is green

**Comment by rokroskar** [comment]
Hi @oleg-nenashev thanks for reporting this! Unfortunately, I'm not sure account merging is possible at the login step - you can, however, link your github account by going to your account settings: 

![Screenshot 2022-12-23 at 10 47 53](https://user-images.githubusercontent.com/3353586/209313546-45181c6e-cdd8-4766-967f-fe50dc05176d.png)


and the to "Linked accounts"

![Screenshot 2022-12-23 at 10 48 42](https://user-images.githubusercontent.com/3353586/209313557-6f31363b-8498-4ca9-b495-8716a13541a1.png)

You should be able to add GitHub there. I'll look into whether Keycloak allows us to merge accounts on login though, that would certainly be a better UX!

**Comment by rokroskar** [comment]
Actually I take that back, it seems that account merging does work already, I just tried it with my own account. Did you try again? In your case it really looks like an error on the server, I will dig through the logs.
