### ISSUE TITLE
Update CLI installation document

### ISSUE THREAD

**Issue by m-alisafaee** [SwissDataScienceCenter/renku#3037]
We should update CLI installation document to check if we should still use `pipx` for local installation or another approach. We should also talk about pre-release versions of Renku CLI and how to install them.

**Comment by mohammad-alisafaee** [comment]
Also check if the suggestion in https://renku.discourse.group/t/local-installation-of-renku-2-3-2-using-pipx-fails-due-to-networkx-dependency/782/12 for a simpler Renku installation inside conda works and use it.

**Comment by rokroskar** [comment]
The CLI is moving to a separate repo with a different installation procedure.
