### ISSUE TITLE
Change visibility of projects through Renku's UI

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku#3065]
**Is your feature request related to a problem? Please describe.**
There is no straightforward way for users to change the visibility of their projects. They need to dive into GitLab to change the visibility.

**Describe the solution you'd like**
Users can change the visibility of their projects through Renku UI.

**Describe alternatives you've considered**
Provide a clear guidance on how users can change the visibility of their projects.

**Additional context**
Users can change the state of their project and should be easily understood: e.g. during development as private and for dissemination as public/internal.

**Comment by Panaetius** [comment]
@lorenzo-cavazzi
