### ISSUE TITLE
Navigation between Gitlab & Projects in Renkulab

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku#3162]
## Motivation

The navigation between gitlab page within Renkulab.io (e.g. https://renkulab.io/gitlab/rok.roskar/flights-tutorial-current) and  Renkulab itself (e.g. https://renkulab.io/projects/rok.roskar/flights-tutorial-current) is not intuitive. 

## Proposal
The top left button could help users to navigate to Renkulab.io instead of staying in Renkulab Gitlab.
<img width="1335" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/127967525/f52b50b0-7ca9-43dd-9b82-1f9180ef0280">

**Comment by aledegano** [comment]
That is indeed the domain of Gitlab: I just checked and unfortunately there seems to be no way of setting a personalized URL when pressing that button.

**Comment by bethcg** [comment]
Would it be then possible to add another button that relates to RenkuLab itself?

**Comment by rokroskar** [comment]
I wonder if we could partially solve this by adding a badge to the project readme?

**Comment by lorenzo-cavazzi** [comment]
That's an interesting idea. I guess we could modify the templates to achieve that since at project creation we can use (or derive) the GitLab URL

**Comment by rokroskar** [comment]
I think this is now obsolete given the Renku 2.0 developments.
