### ISSUE TITLE
Introduce timeout for pending images.

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#318]
Avoid infinite loop if build job is stuck.

See:
https://github.com/SwissDataScienceCenter/renku/blob/b5ecd31df94715329f330479c271eb74045d9b43/services/jupyterhub/spawners.py#L127-L158

**Comment by rokroskar** [comment]
@leafty this check should probably be moved to the notebooks service altogether. The spawner should just receive the instruction for which image to launch and for whom. What needs to happen is to extract the gitlab token from the cookie that the notebook service receives and do this job check there. If the image isn't ready or the job failed, the user should be prompted with the choice to either wait for the image to be built or to launch with a set of pre-defined images.

**Comment by rokroskar** [comment]
moved to https://github.com/SwissDataScienceCenter/renku-notebooks/issues/49
