### ISSUE TITLE
[Docs] Graphviz issue on read the docs

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#324]
See: http://renku.readthedocs.io/en/latest/user/reproducibility.html

Solution is probably linked to part of the conversation from https://github.com/SwissDataScienceCenter/renku/pull/302.

**Comment by leafty** [comment]
Temporarily solved via https://github.com/SwissDataScienceCenter/renku/pull/342

**Comment by rokroskar** [comment]
done in #415
