### ISSUE TITLE
create an image for CI builds

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#326]
We are downloading e.g. docker every time a CI job runs for every project. We need an image with common dependencies to minimize the build times.

**Comment by leafty** [comment]
We should just change the image since python is not used:
https://github.com/SwissDataScienceCenter/renku-python/blob/5ab1f38971580913bfe74718d78552759299ec8c/renku/cli/.gitlab-ci.yml#L12-L23

**Comment by rokroskar** [comment]
Hey that's true... Why are we using the python image?? We probably had some python script in there initially?
