### ISSUE TITLE
[ShapeUp] Initial support spaces which group together other Renku entities

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#3333]
[Pitch on Notion](https://www.notion.so/Exploration-Define-Renku-Projects-and-Users-6f15f7870af04bc9b66362a7936b34cf)

## 🤔 Problem

As a project responsible, I would like to be able to group together multiple repositories so that I can structure my project into multiple repositories.

## 🚞 User stories / journeys

- As a user of RenkuLab, I want to be able to create a space with a name and description
- As a user of RenkuLab, I want to be able to control visibility of the space and give users access to the space
- As a user of RenkuLab, I want to be able to associate repositories to a space

**Comment by rokroskar** [comment]
this has been completed
