### ISSUE TITLE
View all shared projects

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku#3359]
On the Renkulab landing page I have the option to “View all of projects”
![](https://canada1.discourse-cdn.com/free1/uploads/renku/original/1X/c13d6fedb35a0029d8e23c5b64ca676f60d57ead.png)

And when I choose it, I have other options based on the “Authorship” status
![](https://canada1.discourse-cdn.com/free1/uploads/renku/original/1X/c3c3e9ff8b6c31261b309896b0fb579c77b61654.png)

**I would also like to be able to “View all shared projects”** on which I am not the original author but invited as a Maintainer, Developer, Reporter, etc. via Gitlab ([Members of a project | GitLab](https://docs.gitlab.com/ee/user/project/members/)).

Currently I have to extract the “username/projectname” part from the Gitlab link (i.e. https://gitlab.renkulab.io/username/projectname) and paste it to form the corresponding renkulab link (i.e. https://renkulab.io/projects/username/projectname) to be able to access the landing page of the shared Renku project. I don’t see any other way to view a shared project’s landing page without having to resort to this workaround.

I am aware that after having visited a shared project it shows up on my main landing page but as this is limited to showing only 5 projects, it soon disappears if I click on 5 other projects.

This Feature Request stems from [this post in Discourse](https://renku.discourse.group/t/renku-ui-view-all-my-projects-i-e-i-have-access-to-on-gitlab/944).

**Comment by lorenzo-cavazzi** [comment]
Here is the issue that will fix the UI side [#2888](https://github.com/SwissDataScienceCenter/renku-ui/issues/2888).
It requires a few backend adjustments, but they have already been planned and should be ready soon.

**Comment by rokroskar** [comment]
This is superseded by the filters in renku 2.0
