### ISSUE TITLE
notebook: show launch button for group developers

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku#339]
The launch button is shown only for project developers. We should show it also to group (namespace) developers.

- [x] `renku-notebooks` cc @rokroskar @leafty 
- [x] `renku-ui` cc @ciyer @ableuler (https://github.com/SwissDataScienceCenter/renku-ui/issues/254)

**Comment by rokroskar** [comment]
looks like this is closed by https://github.com/SwissDataScienceCenter/renku-ui/pull/280
