### ISSUE TITLE
[ShapeUp] Support Jupyter-free images (2.0)

### ISSUE THREAD

**Issue by sgaist** [SwissDataScienceCenter/renku#3679]
This ticket is to track the work done for the implementation of Jupyter-free images for Renku 2.0.

The goal of this feature is to:

1. Allow different frontends than JupyterLab to be used on the Renku platform
2. Streamline the image creation so it is easier to create an image that can be run on the platform

The following is a list of the tasks for the first round of work:

- [x] Write down new CRD specification for amaltheaSession objects 
- [x] Implement support for the new CRD in Amalthea
- [x] Define (custom) environment configuration separate from the session launcher
- [x] Implement Liveness checks and culling (for determining whether the session is inactive)
- [x] Make existing images work with the new generalized session launcher (new Amalthea)

**Notes:**
- The work is organized in such a way that it should not break any current functionality.
- The implementation will be done iteratively so we will start with a replacement for the current functionality and then build on top of that additional elements to make the feature complete.
- This ticket will be updated following the progress

**Comment by rokroskar** [comment]
@sgaist @olevski I believe everything on this list has been completed?

**Comment by sgaist** [comment]
@rokroskar there are some open tickets on Amalthea but I think the main work can be considered done.

**Comment by rokroskar** [comment]
@sgaist great! can we go ahead and close it?
