### ISSUE TITLE
Phase out gitlab commit button

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#372]
Once git functionality is confirmed to work on Jupyter Lab,
remove the custom git extension installed in `renku/singleuser`.

**Comment by rokroskar** [comment]
is there harm in keeping it there?

**Comment by leafty** [comment]
Yes, if you do `pip freeze > requirements.txt` in your notebook server, the custom button is listed, but cannot be `pip install`ed. This is an issue, because it should be very simple to reproduce work not only from the docker image but also in other setups.

**Comment by rokroskar** [comment]
not using the custom extension anymore.
