### ISSUE TITLE
Run integration tests renku ui/notebooks/gateway/...

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#377]
Most of our recent test failures on Renku have been related to merged PRs in some of the other Renku repositories. Most of the times it is not immediately clear which PR caused the failure which leads time being wasted for debugging. 
Being able to run the the tests also on other repos will save us a lot of time. I think we have to find a solution for this, even if it means moving away from travis. Is GitLab CI/CD the way to go? (https://about.gitlab.com/features/github/)

**Comment by rokroskar** [comment]
> Is GitLab CI/CD the way to go?

No! But this is being solved in #1751 :)

**Comment by pameladelgado** [comment]
> > Is GitLab CI/CD the way to go?
> 
> No! But this is being solved in #1751 :)

Closing as this has been solved.
