### ISSUE TITLE
Pin all versions in code, charts, etc for tagging 0.2.0.

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#400]
Rationale: some of our updates have broken things, e.g. image building or jupyterhub deployment.

- [x] https://github.com/SwissDataScienceCenter/renku-project-template/issues/7
- [x] gitlab version - #401
- [x] renku version #414
- [ ] renku version in singleuser image build https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/helm-chart/chartpress.yaml#L27

**Comment by leafty** [comment]
@rokroskar Confirm we have everything?

**Comment by rokroskar** [comment]
this should have been closed with `0.2.0` release
