### ISSUE TITLE
Evaluate possibility of using https://gitlab.com/charts/gitlab

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku#421]
The GitLab hart is now GA, and most bells and whistles can be turned off.

This can possibly be a replacement for our own GitLab chart, with one caveat: it still requires a wildcard domain. The documentation does not mention how to `helm` it against minikube, so that can also be a problem.

See also: #208 
Note: not high priority.

**Comment by rokroskar** [comment]
I thought there were docs about the chart on minikube? at least we had a conversation about that a few weeks back if I'm not mistaken?

**Comment by pameladelgado** [comment]
closing in favor of #2084
