### ISSUE TITLE
automatically clean up the helm test

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#427]
We should clean up the deployment after running the helm test so we don't have test users lying around. The k8s lifecycle hook on the renku-test container should do this but is not working properly it seems.

**Comment by leafty** [comment]
Would it be possible to run it in the test script?

**Comment by pameladelgado** [comment]
Closing this. We don't define test users by default anymore, furthermore, deployment admins have full control on defining/deleting users used for running acceptance tests with helm if they wish to.
@rokroskar please feel free to re-open if you think this issue is still relevant.
