### ISSUE TITLE
charts: add conditional switch for postgresql

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku#432]
ref. https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/requirements.yaml#L24

this was important during one's site setup, where there is an independent PG instance provided.

**Comment by ableuler** [comment]
@fgeorgatos is this still an issue? If yes, can you please explain a little better what you want here?

**Comment by fgeorgatos** [comment]
@ableuler : I think the original intention was to suppress https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/templates/post-install-job-postgres.yaml and especially execution of `init-postgres.sh`, when PG is provided externally; if so yes, it would eventually be a nice to have.

**Comment by rokroskar** [comment]
There is already a conditional in the chart values.

**Comment by fgeorgatos** [comment]
@rok are you referring to switch `postgresql.enabled`? 
i understand that doesn't address the `post-install` said above - although it would suppress PG itself.

**Comment by pameladelgado** [comment]
Closing in favor of #2122
