### ISSUE TITLE
renku-notebooks-registry was missing for recent install, this could be automated on deployment

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku#435]
fi.
```
kubectl -n renku create secret docker-registry renku-notebooks-registry \
    --docker-server=registry.renku.ch \
    --docker-username=root \
    --docker-password=something \
    --docker-email=root@renku.ch
```

ref. https://github.com/SwissDataScienceCenter/renku/blob/master/charts/renku/templates/registry-secret.yaml#L1
(possibly just document, whenever gitlab is deployed manually)

**Comment by rokroskar** [comment]
I believe this has been done -- reopen if the problem comes up again
