### ISSUE TITLE
Notebook preview in Ku - issue with extension

### ISSUE THREAD

**Issue by marounbs** [SwissDataScienceCenter/renku#436]
Hi all,
This is my first post here, good job on the platform. While we were preparing a demonstration with @erbou, we noticed a bug with the preview of a jupyter notebook. The notebook's filename was "RNAseq.notebook.ipynb" and we weren't able to preview it in the Ku: it was displaying that the file with extension "notebook.ipynb" cannot be previewed. When we changed the filname to "RNAseq-notebook.ipynb" it worked.

**Comment by rokroskar** [comment]
Thanks @marounbs for reporting -- this seems to be a duplicate of https://github.com/SwissDataScienceCenter/renku-ui/issues/328. Could you please check and close this one if that is indeed the case?

**Comment by marounbs** [comment]
Thanks. Yes. Seems to be the same issue. Will close this one.
