### ISSUE TITLE
define the story around branching

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#437]
We need to experiment with various modes of branching, merging and pushing to shared projects and then document solutions to simple problems that will arise. Users are likely to come up against non-trivial problems with merge conflicts that can be resolved quite easily if you know e.g. `renku rebase`.

**Comment by rokroskar** [comment]
One issue that came up was that users were somewhat unhappy about ending up on the `master` branch when launching a notebook server. This makes sense -- they don't necessarily want to push back to master. So one easy change is to automatically create a branch on notebook launch.

**Comment by 3C111** [comment]
Is the master branch protected by default now?  In the UI discussion last group meeting there was the idea to inspire/force users to work from a Ku and branch out automatically (see artist impression below) 
|
ma
| \
|  ku
|    | \ 
|    |  user1
|    |/
| /
|

**Comment by pameladelgado** [comment]
Closing this.
Users are now able to launch notebooks from different branches/commits (solved in [#472](https://github.com/SwissDataScienceCenter/renku-ui/pull/472)).
For a specific requirement, a new issue can be made in `renku-ui` if not [already there](https://github.com/swissdatasciencecenter/renku-ui/issues?q=is%3Aissue+is%3Aopen+branch).
