### ISSUE TITLE
Create and curate data projects for renku tutorial

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#438]
For the renku tutorial, we need to work with the data science team to prepare and curate the data repository projects for each of the datasets that will be used. 

- [ ] University enrollment data (@3C111)
- [ ] Swiss parliament data (@jirikuncar)
- [ ] Genomics (@leafty)
- [ ] Zürich/Swiss open data (@ableuler, @fgeorgatos)

**Comment by fgeorgatos** [comment]
@ableuler: my pick for now among Swiss open data is probably this one (1st try, only spent few mins): https://opendata.swiss/en/dataset/solarenergiepotenziale-der-schweizer-gemeinden/resource/5c1fbbc3-96dc-4414-831b-290b6d482791

**Comment by rokroskar** [comment]
There was also some discussion from @ebiiii and @leafty about using SBB data -- that might be a good one since we already have examples from the data science course.

**Comment by ableuler** [comment]
@fgeorgatos I like the solar data, especially their interactive application. But the data that you can download seems to give you only the total potential for solar power per municipality. Not sure we can do a fun project with that.

**Comment by fgeorgatos** [comment]
@ableuler : you are right, now that I dive into it, it is much less than I understood via their WUI :-(

**Comment by fgeorgatos** [comment]
@ableuler : and since we're into some tiller-powered business, how about something in relation to wind or even wind-gusts? https://opendata.swiss/en/dataset/windatlas-schweiz-jahresmittel-der-modellierten-windgeschwindigkeit-und-windrichtung-in-125-m-h

**Comment by ableuler** [comment]
Ok, I did a bit of brainstorming and some phone calls. 

**SBB data**
- For me a first option would be to use the SBB for delay prediction. If we come up with a model that we can feed with the latest data from SBB every few months and wrap it in an app for the public, that would be awesome! One could even see it as a feasibility study for SBB to see if they can add a probability indication that you will make your connection when they search connections for you.

**Open Data Zurich**
Marco Sieber from Open Data Zurich was really friendly (I'm visiting them in a few weeks to establish contact). He suggested a few things:
- Delay prediction (again) for VBZ. They've already tried during a R hackday: https://github.com/OpenDataDayZurich2016/ODDPredictDelays. According to him VBZ is really into those things. Furthermore their delays might be easier to predict as they are more dependent on external factors (traffic, weather) than those of SBB which I imagine to depend more on their time-table itself which changes every year.
- Pedestrian/Bike data, study the effect of weather, potential construction sites nearby (not sure if we could get data on this) on the behaviour of people.

**Swisstopo**
Another type of data that would be a lot of fun to tackle is aerial photos of Switzerland. The publicly available version has a resolution of 25m (going back quite a bit in time), but through an ETH portal (the lady at swisstopo was only slightly condescending when pointing me to it) we also have access to 25cm resolution arial pictures for all of Switzerland. Possible questions that come to my mind here:
- Add municipal boundaries and try to predict average/median income/net worth (whatever we could get our hands on) per municipality based on arial picture. @fgeorgatos Didn't Greece at some point use arial pictures (swimming pools!) to estimate tax evasion?
- Counting cows. Everybody can count cars, right? :) I'm sure we could also get actual data on cows (for Zurich I've seen it) to compare. Are cows in some regions of CH more likely to be outside than in others?

**Comment by rokroskar** [comment]
Those are great suggestions - can you please approach Fernando to settle on an option? Delay prediction could be using either sbb or vbz so that seems like an obvious choice to me.

**Comment by fgeorgatos** [comment]
@ableuler , while on swisstopo:
* well, in general online data has been used over last years, but pools in online maps kind of stick out!
* cows? that rings a bell, yes, a bell :) I've read a claim online that cows tend to face north-south (or towards sun in general) instead of other directions; this is perhaps an important question to resolve! ;-)
