### ISSUE TITLE
config value `urlPrefix`better be renamed to `urlPathPrefix `

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku#465]
probably uncomplicated, todo in a 2nd moment

**Comment by rokroskar** [comment]
more info is needed here -- which value are you talking about?

**Comment by fgeorgatos** [comment]
this was about `urlPrefix: /gitlab`, 
however that definition is coming from the helm chart, so probably we don't want to change it for now.

Closing as stale and not actionable atm (with current 3rd-party chart).
