### ISSUE TITLE
build user docker images only when needed

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#476]
We could use the new feature of gitlab CI to build images only when something changes with the environment: https://about.gitlab.com/2018/10/22/gitlab-11-4-released/#run-jobs-codeonlycodecodeexceptcode-for-modifications-on-a-path-or-file

Two changes needed:

- [ ] provide an API that would return the image needed for a desired commit (https://github.com/SwissDataScienceCenter/renku-notebooks/issues/101)
- [ ] modify the project template's `.gitlab-ci.yml` file

**Comment by leafty** [comment]
:+1: but it needs some documentation to help have the right change filters

**Comment by rokroskar** [comment]
yes I was thinking we could have an `/env` so that would be the default path we watch and we would document inside the ci file how to add additional paths.

**Comment by rokroskar** [comment]
Related to https://github.com/SwissDataScienceCenter/renku-notebooks/issues/101

**Comment by pameladelgado** [comment]
added User label, based on the experience of a user who modified a line in a readme and got an hour worth of docker building image (also related to missing cached in the runner).

**Comment by rokroskar** [comment]
They should be more conservative with their readme files! :) jk, we should address this asap, it's been coming up a lot!

**Comment by ableuler** [comment]
I would propose to first try and leverage the build cache in combination with the `latest` tag as described [here](https://github.com/SwissDataScienceCenter/renku/issues/788#issuecomment-619040047). Hopefully this could speed up the build so much that it would free us from a need to introduce additional conditions into the gitlab ci files.

**Comment by rokroskar** [comment]
Using the build cache is still not very quick. It has to check all the layers which is cheaper than building them but nontrivial. It solves the problem of having to rebuild from scratch if the previous image is not available on the runner, but it still takes a few minutes for large images.

**Comment by ableuler** [comment]
I was thinking that some combination of local cache and using the registry as cache could result in fast builds most of the time and occasional builds where the layers have to be pulled from the registry first. But I'm really not sure if that will work. Otherwise skipping unnecessary builds completely is the way to go.

**Comment by pameladelgado** [comment]
Closing. I'd say this has been addressed with the [ability to pin docker images](https://renku.discourse.group/t/how-to-pin-a-docker-image/240) functionality.

**Comment by rokroskar** [comment]
I'm not sure it has, they serve slightly different purposes. I might still want to build images for my project but not all the time (only when relevant things in the repo change). We can reopen at a later point if we decide to go down that route again.
