### ISSUE TITLE
Installing iGraph with C core on Mac OS X using Homebrew

### ISSUE THREAD

**Issue by sjinko** [SwissDataScienceCenter/renku#495]
Hi,

I’m trying to install the python-igraph module via pip install -r requirements.txt
But on Mac OS X the python-igraph module requires the C core (https://igraph.org/python/)
In the iGraph docs. the C core is installed using Homebrew.
How can I install the C core using Homebrew?

For now, when I do “pip install -r requirements.txt,” the terminal returns: “Could not download and compile the C core of igraph.” (https://pastebin.com/7LmsdXnr)

> ## iGraph Installation on Mac OS X
> Instead of letting pip compile the C core for you, you can install Homebrew and the homebrew/science/igraph formula. This will ensure that the C core is found by pip so running pip install python-igraph will compile the Python interface only and link it to the C core.
> Source:
> - https://igraph.org/python/

**Comment by rokroskar** [comment]
Hi @sjinko -- apologies for the late response, xmas holidays got in the way :) 

I'm somewhat confused by your question: are you trying to install iGraph on your local machine or on renkulab? On mac, the easiest is to install homebrew (https://brew.sh/) and do `brew install igraph`. Then install the python package with `pip3 install python-igraph`. I just tried this and it worked out of the box.
