### ISSUE TITLE
Logging into Renku Cloud using GitHub

### ISSUE THREAD

**Issue by StuartWheater** [SwissDataScienceCenter/renku#496]
To log into Renku Cloud using a GitHub account, "Full Access" (read/write?) to Personal User Data is requested:

> Personal user data
> Full access
> This application will be able to read and write all user data. This includes the following:
> 
> Private email addresses
> Private profile information
> Followers

Is "Full" access actually required or have I misinterpreted this?

**Comment by rokroskar** [comment]
Hi @StuartWheater, thanks for reporting this. Indeed, we do not need full access to the GitHub account, as we are only using GitHub for identifying the user. It was a misconfiguration that has gone unnoticed but is now fixed. Thanks again!
