### ISSUE TITLE
Create a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#500]
- Describe format for PRs
- Describe expectations for individual commits in PRs

**Comment by jirikuncar** [comment]
We have a template in https://github.com/SwissDataScienceCenter/renku-python/blob/master/CONTRIBUTING.rst

**Comment by rokroskar** [comment]
@jirikuncar that's a good start -- I wanted to give some more specific guidelines for PRs (e.g. linking to issues, how to write the descriptions) and commit messages. @ciyer also mentioned that it would be nice to structure PR descriptions in such a way that would make it possible to more or less auto-generate change logs for releases.

**Comment by jirikuncar** [comment]
>  it would be nice to structure PR descriptions in such a way that would make it possible to more or less auto-generate change logs for releases.

I would rather use commit messages or https://pypi.org/project/towncrier/
