### ISSUE TITLE
Review standard Renku realm in keycloak

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#514]
The standard keycloak realm which is created for a fresh Renku keycloak instance should be modified such that the `aud` claims of access tokens issued by keycloak contains the `client_id` of the respective client application. See also https://github.com/SwissDataScienceCenter/renku-gateway/issues/90. Note that this configuration will allow Renku to run with newer Keycloak versions but also works with older Keycloak versions (eg 4.5.0).

**Comment by pameladelgado** [comment]
Closing, as this seems to be fixed now. 
Both [renku](https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/renku/templates/_keycloak-clients-users.tpl#L23) and [renku-cli](https://github.com/SwissDataScienceCenter/renku/blob/master/helm-chart/renku/templates/_keycloak-clients-users.tpl#L46) Keycloak clients have their respective mappers configured as needed. Another related PR: [#662](https://github.com/SwissDataScienceCenter/renku/pull/662).
