### ISSUE TITLE
Unify Renku clients in Keycloak

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#519]
We currently have too many client applications registered in Keycloak. These are loaded from our template realm when a new instance of Renku is deployed and most of them are not even used. We should have only the following two client applications:

- A Renku client to be used by the gateway (UI) potentially the CLI, etc
- A GitLab client to be used only by GitLab.

Keeping these two clients separate is important for deployments agains existing GitLab instances.

**Comment by ableuler** [comment]
After merging #662, the only thing left to do here is to rename the `gateway` client to `renku` and potentially `gitlab` to `renku-gitlab`.

**Comment by rokroskar** [comment]
Can we finish this one up to close out the keycloak-related work?
