### ISSUE TITLE
Enable "pages" in Gitlab

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku#532]
https://gitlab.com/ allows for creating pages
![image](https://user-images.githubusercontent.com/4173925/54696873-e5597480-4b2c-11e9-8c2c-0aa349d123a9.png)
Is it possible to have the same service on the Renku side?
![image](https://user-images.githubusercontent.com/4173925/54696895-f3a79080-4b2c-11e9-8cc7-7866a37e24cb.png)

[It would be nice to be able to use Renku to write an e-book about Renku, not unlike https://gitlab.com/cchoirat/renku, https://cchoirat.gitlab.io/renku/].

**Comment by cchoirat** [comment]
Another use case could be R package development: the associated documentation of an R package can be created with https://pkgdown.r-lib.org/, as https://ggplot2.tidyverse.org/.

**Comment by rokroskar** [comment]
Why not contribute that content to the renku documentation instead?

**Comment by cchoirat** [comment]
Because I'd like to have this feature to develop R packages from a R-dev
type of image and generate a package doc such as
https://ggplot2.tidyverse.org/.

**Comment by rokroskar** [comment]
I don't quite understand the use-case of renku for package development - what is the benefit over sticking with "vanilla" gitlab.com or github?

**Comment by cchoirat** [comment]
Adding @emmjab 

I would really like to have the pages enabled.  Two reasons:

1. R package documentation.  To follow up with your question @rokroskar , developing an R package might require a setup (say a specific version of Java + LaTeX + ...) that can be quite tedious (and no, Docker + GitLab is not an option for most users), so it would be nice not to have any local config that goes from dev to doc publishing.
2. Write about Renku from renkulab (in the spirit of https://cchoirat.gitlab.io/renku/).

**Comment by rokroskar** [comment]
It's not a trivial engineering effort to support this - could you mirror the project on gitlab.com and configure pages there?

**Comment by cchoirat** [comment]
I guess so, that's right!

**Comment by cchoirat** [comment]
I will give it a try and report back.

**Comment by rokroskar** [comment]
You should be able to configure a push mirror from the renkulab gitlab

**Comment by gavin-k-lee** [comment]
Thanks to @cchoirat - I wrote up a little guide:

https://renku.discourse.group/t/how-to-publish-to-gitlab-pages-using-renkulab/302/2
