### ISSUE TITLE
Update minikube-values.yaml to include graph in global section

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#534]
Global section should include:
```  graph:
    tokenRepository:
      postgresPassword: *graph_token_repo
```

**Comment by jachro** [comment]
@pameladelgado isn't good enough what we currently have in master:
https://github.com/SwissDataScienceCenter/renku/blob/e09db064666127514082908fedd75b17b6ecfa3a/charts/minikube-values.yaml#L30

**Comment by pameladelgado** [comment]
@jachro yes it is. Apparently I looked at a local-non-updated version of that file :sweat_smile: 
Thanks for looking into this!
