### ISSUE TITLE
inconsistent Dockerfile and gitlab_ci.yml

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku#540]
After changing the Dockerfile, the renku cli was not in sync with the version used in the gitlab CI, and that caused the dot build to fail. E.g. ```renku/singleuser_r:latest``` in Docker, and 
```renku/renku-python:v0.4.0``` in the gitlab-ci.yml.

Depending of how this is going to be handled in future versions, we should document the fix, or find a way to prevent this situation from happening.

**Comment by rokroskar** [comment]
In future versions there will be no more dot file building because the graph will be live. But until the access control issues are resolved, I suppose we could continue building the dot file for private projects that do not want to publish the graph data.

**Comment by gavin-k-lee** [comment]
bump: Is this solved now?

**Comment by rokroskar** [comment]
indeed, this is no longer relevant.
