### ISSUE TITLE
Create documentation for Renku admins

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#547]
- [ ] Document steps / requirements before installing Renku on 
0. Minikube ?
1. Local cluster/VMs
2. Openstack
3. Openshift
4. AKS

- [ ] Make templates for renku-values.yaml and related files for Renku deployment, put them in the public repo:
https://github.com/SwissDataScienceCenter/renku-admin-docs

**Comment by ableuler** [comment]
A section on known problems / troubleshooting would be good. The problem with upgrading Keycloak to `>=4.8` should be mentioned there, pointing to https://github.com/SwissDataScienceCenter/renku-gateway/issues/90 for resolution.

**Comment by rokroskar** [comment]
@pameladelgado do you have a draft of the docs? If so, please make a PR and we can start iterating on it
