### ISSUE TITLE
Remove duplication in values.yaml files

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#549]
Currently, we maintain (or should maintain) many specific `xyz-values.yaml` files (minikube, minikube with gitlab as backend, etc.). These are annoying to maintain. To fix this we should move those values which are identical for all our deployments to the `values.yaml` file which is packaged with the chart. In my opinion it does not make much sense to have everything commented out there - reasonable defaults should be set there. Furthermore, we should make use of the fact that helm supports the usage of multiple additional values files:

> You can specify the ‘–values’/‘-f’ flag multiple times. The priority will be given to the last (right-most) file specified. For example, if both myvalues.yaml and override.yaml contained a key called ‘Test’, the value set in override.yaml would take precedence:
```
$ helm install -f myvalues.yaml -f override.yaml ./redis
```

**Comment by pameladelgado** [comment]
Closed via #673
