### ISSUE TITLE
Renku Alternatives

### ISSUE THREAD

**Issue by brunowego** [SwissDataScienceCenter/renku#588]
I really like renku stack! Congrats creators. I'm looking for alternative, just for compare. Perhaps you guys have a know list of possible platforms with same kind of objective?

**Comment by ciyer** [comment]
I have been working on exactly this in preparation for a presentation at SciPy 2019!

  https://github.com/SwissDataScienceCenter/r10e-ds-py/blob/master/notebooks/02-Tools.ipynb

You'll see that it is still work-in-progress, but I would be interested to hear your comments if you have any.

**Comment by rokroskar** [comment]
Thanks for the enthusiasm @brunowego! :) Would be happy to get any feedback you might have. 

@ciyer we should probably pour that information into the docs somehow.

**Comment by brunowego** [comment]
Thanks a lot for your references @ciyer. Exactly what I was looking for.
