### ISSUE TITLE
Notebook interactions

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku#595]
Users experience when interacting with notebooks should be improved

### Notebooks table
* Update layout and add more interactions: view logs, stop failing notebooks
  SwissDataScienceCenter/renku-ui#499, SwissDataScienceCenter/renku-ui#414, SwissDataScienceCenter/renku-ui#361
* Add links to relevant GitLab pages
  SwissDataScienceCenter/renku-ui#493
* Add polling capability to notebooks related components
  SwissDataScienceCenter/renku-ui#559

### Start notebooks
* Improve page layout according to server options
  SwissDataScienceCenter/renku-ui#482

**Comment by rokroskar** [comment]
This epic has turned into a dumping ground for a big range of interactive session improvements - closing in favor of more focused and manageable epics.
