### ISSUE TITLE
Autosave on JupyterLab

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku#596]
Unsaved users' work on JupyterLab should be autosaved and pulled again the next time the user tries to start a new notebook from the same branch/commit combination

**Comment by pameladelgado** [comment]
I think there's a typo: is JupyterLab :grin:

**Comment by lorenzo-cavazzi** [comment]
Right, we are not talking about the planet here :smile: Thanks!

**Comment by rokroskar** [comment]
Looks like this is complete? Can it be closed?

**Comment by lorenzo-cavazzi** [comment]
Right, it can be closed (:-1: to the epics not auto-closing when all the relates issues are closed)
