### ISSUE TITLE
Use renku with existing project and problems with renku rerun

### ISSUE THREAD

**Issue by guist** [SwissDataScienceCenter/renku#604]
Hello,

I am working on a machine learning project, which is stored locally on my computer, and I would like to try renku on it. Since I am not downloading the scripts and the data from the internet, I was wondering how to proceed. Should I just go to the project directory and type the following commands?

`renku init`
`renku dataset create my-dataset`
`renku dataset add my-dataset path/to/dataset`
`renku run python main.py`

Thank you very much for your answer.

Best regards,
Guillaume

**Comment by rokroskar** [comment]
Hi Guillaume, is your project already in a git repository? If so, you will need to use `renku init --force` which will add some things to the repo. 

Does your script take parameters? Renku works by interpreting the options/parameters you specify on the command line - this is especially important if the script is consuming data because that's the only way that we can construct the knowledge graph.

**Comment by guist** [comment]
Thanks for the answer.

The project is already in a git repository so I will add the --force flag as you mentioned above.

For now, the script does not take any options/parameters. When I run it, the following steps are processed:
-loading data stored locally
-pre-processing
-extracting features
-training a model
-calculating scores on test data based on cross-validation 

When you write that the parameters have to be specified in the command line, what exactly do you mean? Are you talking about the possible values of the hyperparameters determined during the training?

**Comment by rokroskar** [comment]
To make this project more renku-like, I would suggest refactoring your script into smaller scripts that each does one of the steps in your list (i.e. data loading, pre-processing etc.). Ideally these scripts would also consume input arguments that would specify where to read the data from - this way, renku can build a dependency graph for your pipeline. The parameters can be hyperparameters or data inputs.

**Comment by rokroskar** [comment]
Aha great - then it sounds like basically what you need to do is replace the main script by a series of `renku run` commands.

**Comment by guist** [comment]
I created a dataset as follows, which worked.
`renku dataset create labels`

Then, I tried to associate a csv file stored locally on my laptop.
`renku dataset add labels path/to/csvfile`

But I got an error: "Ahhhhhh! You found a bug", asking me to open an issue.

Could you please tell me what to do? 

By the way, I had no problem when I created the zhbikes dataset with the url.

**Comment by ciyer** [comment]
Could you send us the stack trace for the bug? 

BTW, it is not *actually* necessary to create a dataset. Though datasets are nice longer term, since you can add metadata to then, but if you just want to try things out, you can copy the csv file to your repo and add it to git (or git-lfs). That is sufficient for running `renku run`.

**Comment by guist** [comment]
Thanks, I found where the error came from. I provided a wrong path to the data file, which could not be read. Now it is working, I could create the dataset.

Concerning the other part of my question, I split my main script into two sub-scripts (load_and_preprocess_data.py and pipeline.py and I wrote the following commands:

`renku run python load_and_preprocess_data.py path_to_data path_to_labels ../data/X.npy ../data/y.npy`
`renku run python pipeline.py ../data/X.npy ../data/y.npy hyperparameter1 hyperparameter2 hyperparameter3 path_folder_output` 

Both commands worked and I saw that some files were created in the .renku/workflow/ folder.

Now I would like to rerun the script pipeline.py. Since it contains a nested cross-validation and the 10 folds are randomly built, I don't use `renku update`
but 
`renku rerun output1 --with-siblings` 

This gives me a bug with the following message:

```
Traceback (most recent call last):
  File "[...]/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/rerun.py", line 154, in rerun
    outputs=outputs,
  File "[...]/renku/cli/_graph.py", line 531, in ascwl
    raise NotImplementedError('Can not connect subdirectory')
NotImplementedError: Can not connect subdirectory
```

I don't understand this error. Could you please tell me how to proceed? Thanks!

**Comment by emmjab** [comment]
Hello @guist , there may have been a bug in the past, but in the most recent version of `renku` this appears to work!

You can either `pipx upgrade renku` to 0.9.1 or swap out the image in your Dockerfile by replacing the first line with:
```
FROM renku/singleuser-base:ae4dbc5-renku0.9.0
```

I tested a call with `renku rerun` in this notebook here: https://renkulab.io/projects/emma.jablonski/minimal-renku
```
$ renku rerun outputs/goodbye.txt 
Error: There are missing output siblings:

        outputs/sibling.txt

Include the files above in the command or use the --with-siblings option.
jovyan@jupyter-emma-2ejablonski-minimal-2drenku-2dbf584d0f:/work/minimal-renku$ renku rerun outputs/goodbye.txt --with-siblings
Resolved '.renku/workflow/a18b6af299e04666bea63759af0486a1.cwl' to 'file:///work/minimal-renku/.renku/workflow/a18b6af299e04666bea63759af0486a1.cwl'
[workflow ] start
[workflow ] starting step step_1
[step step_1] start
[job step_1] /tmp/tsadmy9i$ python \
    /tmp/tsadmy9i/scripts/run.py \
    outputs/goodbye.txt \
    outputs/sibling.txt
[job step_1] completed success
[step step_1] completed success
[workflow ] completed success
Unchanged files:

        outputs/sibling.txt
```

Let us know if this is working for you!

**Comment by rokroskar** [comment]
Closing this for now - please reopen if the issue persists.
