### ISSUE TITLE
Allow a non-team member of a public project to start a notebook

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku#605]
As a user, I would like to be able to start a notebook from a public project of which I am not a team member.

* I want to be warned that the project is read only (mode indicator, or when notebook is started)
* I must not be allowed to push to the project

Optionally:
* If I am added to the team, I can push to the project
* I can save my changes on a new (forked) project

This is related to issue SwissDataScienceCenter/renku-ui#510

**Comment by rokroskar** [comment]
This is maybe not a trivial change. Somewhere we need to store additional information about what sort of special permissions the owner of the project wants to grant. This could be done:

* by storing some value in a GitLab project environment variable, e.g. `ALLOW_EXTERNAL_LAUNCHES`
* by storing a value in the project configuration that is a part of the repository. The UI would need to parse this value and pass it along with the other `server_options`. We would need to have some way of preventing someone from spoofing that request though.

**Comment by erbou** [comment]
* Environment variable are specific to an instance, if the project is forked/copied, the decision is not (AFAIK) carried to the new project
* Environment variables are not limited to a project scope, and can have a group scope (e.g. group default policy).
* Storing the value in the project config, e.g. ./renku/config would mean that the decision to allow decision launches is inherited if the project is forked/copied

The access control is usually something that is decided by the project owner, not something that should come by default with the project. The prudent approach would thus point to the env variable option. But this is to be weighted with the robustness of the respective methods to prevent someone from spoofing the request.
