### ISSUE TITLE
Broken Travis (?) badge

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku#610]
![image](https://user-images.githubusercontent.com/4173925/61533832-3a02f280-aa2e-11e9-8f64-340ccfcb420d.png)

**Comment by rokroskar** [comment]
Don't see that... 

![image](https://user-images.githubusercontent.com/3353586/61547048-e2bf4b00-aa4a-11e9-93a6-70b88726f998.png)

**Comment by rokroskar** [comment]
sometimes the badge doesn't show up, but this seems to be a travis problem.
