### ISSUE TITLE
Redesign the R templates

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#621]
The purpose of the redesign of the R templates is to make it easy for users to use the latest version of R, which updates frequently, and whose users expect to be able to use the most recent version. The current image installs R/Rstudio via conda, whose version doesn't keep up with the latest.

To solve this, we can use rocker base images and load renku and jupyter on top. This will also involve handling the entrypoint path for the project in the Rstudio env w/.Rprofile.

**Comment by rokroskar** [comment]
This epic is complete - for the additional issues that were added to it regarding templates we already have another epic open.
