### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#630]
The collaboration features in Renku need to be better organized and structured. These features include: Kus, Merge Requests (Pending Changes), Recent Activity, Contributors.

First, Kus and Merge Requests do not need to be in the top level navigation of a project. We should have one tab, *Collaboration*, with Kus, Merge Requests, and the other features as they become available as sub tabs.

**Comment by rokroskar** [comment]
Closing this epic since all the issues are done. If we revive the topic in the future we can reopen the epic and add new issues.
