### ISSUE TITLE
"Back to renku-ui" from profile page is confusing

### ISSUE THREAD

**Issue by pdurbin** [SwissDataScienceCenter/renku#641]
I clicked on my profile and noticed "Back to renku-ui" at the top. It looks like this:

![Screen Shot 2019-08-28 at 10 13 01 AM](https://user-images.githubusercontent.com/21006/63863663-984fb900-c97c-11e9-9130-0d11665fe8d6.png)

I would suggest changing this to "Back to Renku".

**Comment by ableuler** [comment]
Thanks for the suggestion. What's displayed here is simply the id of the client application which is registered in Keycloak. We're consolidating the client applications (#519) we use in Renku and after this, the main one should indeed be called "renku".

**Comment by gavin-k-lee** [comment]
Obsolete with new UI
