### ISSUE TITLE
Project metadata to contain more information

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku#651]
As a Renku owner, I should be able to find more information about Renku project from the KG. Such information should be `name` and `creator`. The `name` should have the `<namespace>/<project-name>` format so it's matching GitHub project naming and it's easy queryable.

**Comment by rokroskar** [comment]
The two issues in this epic are complete - can we close it @jachro?

**Comment by jachro** [comment]
I think so. Do you want me to do it?

**Comment by rokroskar** [comment]
Indeed! :)

**Comment by jachro** [comment]
All done so closing...
