### ISSUE TITLE
Investigate if upcoming helm 3 changes are a factor in charts refactoring..

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku#655]
Helm v3 has been released in beta recently (ref. https://helm.sh/blog/helm-v3-beta/). There are some interesting new features which could help us to improve our charts. Two potentially promising ones are:

_1. JSON schemas can now be imposed on chart values and bundled with the chart. The schemas can be used for validating chart values._

This could help by detecting wrong values already at template rendering time and thus improve the experience for someone trying to deploy Renku.

_2. Helm now supports [library charts](https://helm.sh/blog/helm-3-preview-pt6/). These charts are not meant to be installed but can be depended on and referenced by other charts. These were inspired by the common chart in the incubator repository._

This feature could help us to remove some of the boilerplate usually introduced by `helm create` from the charts.

**Comment by Panaetius** [comment]
```Helm now supports library charts. These charts are not meant to be installed but can be depended on and referenced by other charts. These were inspired by the common chart in the incubator repository.```

These (and `common-chart`) could be great to simplify templates.

**Comment by rokroskar** [comment]
What is the expected outcome here? Charts revised for helm3? That seems like quite a large effort. Or is there another goal?

**Comment by fgeorgatos** [comment]
i can provide a first outline answer:
- `JSON schemas` will solve a long declared need, to vet values early in the process
- `library charts` could help to reduce LoC of existing charts

However, these would become feasible once help 3 is out, which is not the case yet, 
therefor it is wise to postpone this issue for a future milestone/sprint.

**Comment by rokroskar** [comment]
can we close this then?

**Comment by fgeorgatos** [comment]
doing so now then
