### ISSUE TITLE
Assign a service URL to the UI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#676]
Currently, the Renku UI is served under the main platform URL. In oder to free URIs like `https://<some-renku>/datasets/:id>` to serve as IDs for entities, we should serve the UI under a subdomain or behind a path prefix, presumably `www.` or `/ui`.

**Comment by ciyer** [comment]
We should also consider URIs of the form  ```https://<some-renku>/entity/datasets/:id```

**Comment by ableuler** [comment]
Yes, using URLs like `https://<some-renku>/entity/datasets/:id` as IDs could leave URLs like `https://<some-renku>/datasets/:id` to the UI. If you have a strong preference for that option instead of what's proposed here, the epic #674 might be the better place to discuss it.

**Comment by rokroskar** [comment]
If we don't need a service URL for the UI, can we close this issue?
