### ISSUE TITLE
docs: add docs for running renku/jupyterlab from a local docker image

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#688]
**Is your feature request related to a problem? Please describe.**
The third way to develop projects with renku (i.e. in addition to (1) online development in the jupyterlab spawned by renkulab.io; and (2) offline local development) is offline using the docker image for the project stored in the renkulab registry. In contrast to normal local development, you can be sure that by running from your docker image, your development environment will match what you're sharing on renkulab (i.e. won't conflict with versions of sw on your local machine, won't require you to manually install missing dependencies/activate a conda env/etc.).

**Describe the solution you'd like**
Documentation for this case.

**Comment by ableuler** [comment]
This would be great! I think this could go into a `working locally` section on readthedocs. The first and short part of that section would just describe how to clone the project and create a virtual environment from the project dependencies. The second section would describe what you've detailed above.

**Comment by emmjab** [comment]
There used to be a `renku image` command I think... I don't see one now...

```
% renku -version
0.9.0
% renku --help
Usage: renku [OPTIONS] COMMAND [ARGS]...

  Check common Renku commands used in various situations.

Options:
  --version                       Print version number.
  --global-config-path            Print global application's config path.
  --install-completion            Install completion for the current shell.
  --path <path>                   Location of a Renku repository.  [default:
                                  (dynamic)]
  --renku-home <path>             Location of the Renku directory.  [default:
                                  .renku]
  --external-storage / -S, --no-external-storage
                                  Use an external file storage service.
  --disable-version-check         Do not periodically check PyPI for a new
                                  version of renku.
  -h, --help                      Show this message and exit.

Commands:
  clone     Clone a Renku repository.
  config    Manage configuration options.
  dataset   Handle datasets.
  doctor    Check your system and repository for potential problems.
  githooks  Manage Git hooks for Renku repository.
  help      Show help message and exit.
  init      Initialize a project in PATH.
  log       Show logs for a file.
  migrate   Migrate to latest Renku version.
  mv        Move files and check repository for potential problems.
  rerun     Recreate files generated by a sequence of ``run`` commands.
  rm        Remove files and check repository for potential problems.
  run       Tracking work on a specific problem.
  show      Show information about objects in current repository.
  status    Show a status of the repository.
  storage   Manage an external storage.
  update    Update existing files by rerunning their outdated workflow.
  workflow  List or manage workflows with subcommands.
```

**Comment by gavin-k-lee** [comment]
Does https://renku.readthedocs.io/en/latest/user/interactive-running-locally.html close this issue?

**Comment by rokroskar** [comment]
Nice, you've found all the duplicates 😆
