### ISSUE TITLE
docs: add FAQ section

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#699]
**Is your feature request related to a problem? Please describe.**
There are some frequently asked questions that may be answered in the documentation but come up often and aren't easy to find.

**Describe the solution you'd like**
A top-level FAQ section like other projects have (https://docs.docker.com/engine/faq/, https://mybinder.readthedocs.io/en/latest/faq.html)

**Describe alternatives you've considered**
"Better organized documentation" we need to do this too, but it's usually good to include information in different forms because people have different entrypoints to solving problems that turn out to have the same solution.

**Comment by rokroskar** [comment]
We already have this under [troubleshooting](https://renku.readthedocs.io/en/latest/user/troubleshooting.html) - feel free to add to it and/or rename it. I will close this issue but feel free to reopen if a more specific change is needed.
