### ISSUE TITLE
Storage for UI State

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku#712]
# Description

The UI needs a way to store state information. Examples include:
* Has a user already seen new release notes?
* Has a user opted-out of KG integration for a project

There may not just be one location for this information, but the UI needs a way of addressing storage and managing information saved there

**Comment by lorenzo-cavazzi** [comment]
During the last design meeting (further info here: https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/98107399/2020-01-09+Design+meeting+notes) we agreed on using the `renku-gateway` Redis instance to store this user-related metadata persistently in JSON format. The backend APIs will be in `renku-gateway` as well.
