### ISSUE TITLE
Support for nested groups when creating new project

### ISSUE THREAD

**Issue by JamesRunnalls** [SwissDataScienceCenter/renku#716]
In organising larger projects sometimes nested groups are required. Currently, renku can handle just one level of grouping and you need to use gitlab in order to move it further into a folder structure. 

Can it be possible to select a nested group when creating a new project?

**Comment by JamesRunnalls** [comment]
Since the most recent update to the renku ui - if you try to access a repo nested more than once you can view it in the list of the projects but if you try to open it you get a 404 not found error.

**Comment by ciyer** [comment]
Yes, I can see how the changes we made could cause a 404 on a nested project. We will work on fixing that problem ASAP to make it at least possible to use Renku on those projects.

Adding support for creating projects in nested groups will take a bit more time, but it makes sense as a feature, and we will take that up soon.

**Comment by rokroskar** [comment]
@ciyer can this be closed?

**Comment by ciyer** [comment]
Not yet. The problem with display/routing of these projects has been fixed (though as of 10 Jan not yet deployed on Renkulab), but James would also like to be able to select a nested group when creating a new project. That has not yet been implemented.

**Comment by rokroskar** [comment]
Got it, thanks!

**Comment by ciyer** [comment]
@JamesRunnalls We have deployed an update the Renkulab that fixes the display bug. You should be able to open and view projects in nested subgroups in the UI again.

Support for creating projects in nested subgroups will come a bit later.

**Comment by JamesRunnalls** [comment]
Great thanks @ciyer

**Comment by ciyer** [comment]
Fixed by #703
