### ISSUE TITLE
fix the bug report template

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku#727]
Can we modify the bug report to the below? (open to other opinions)

**Describe the bug**

**Link to project**
If possible, provide a public renkulab link to the project with the bug.

**To Reproduce**

**Expected behavior**

**Screenshots and/or execution output**
If applicable, add screenshots and/or to help explain your problem.

**Run environment**
 - local terminal OR renkulab browser
 - specify RStudio / Jupyterlab / Other

**Run environment (please complete the following information):**
 - renku-python version
 - browser [e.g. chrome, safari]

**Additional context**

**Comment by rokroskar** [comment]
yep! please open a PR - thanks!
