### ISSUE TITLE
Cannot view/edit cell tags or metadata in jupyterlab

### ISSUE THREAD

**Issue by Kriegelw** [SwissDataScienceCenter/renku#729]
I attempted to see how the cells were tagged for the tutorial to make the connection of the parameters but could not find the option in jupyterlab while it exists in jupyter notebook.

**Comment by Kriegelw** [comment]
The way I solved the issue was to got to 'Help' -> 'Launch Classic Notebook' to view and edit the tags. I have not yet found a way to do so in jupyterlab.

**Comment by ciyer** [comment]
Though it is not at all obvious, it is possible to do in the JupyterLab UI.

![image](https://user-images.githubusercontent.com/1196411/73003603-2f268180-3e06-11ea-88d2-26111a99920f.png)

But, yes, doing this is easier in the classic notebook.
