### ISSUE TITLE
Default path of R projects

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku#735]
I will use https://renkulab.io/projects/cchoirat/rpath/ as an illustration.  Thanks to @gmartinezmirai for his great work!

**Is your feature request related to a problem? Please describe.**

When I start an RStudio interactive environment, the default working directory is  `/home/rstudio`.

**Describe the solution you'd like**

I would like two things.

1. The default working directory should be `/work/rpath`.

2. If there is an `.Rproj` file available (in most cases, it will be called `rpath.Rproj`), it should be opened when RStudio starts.

**Describe alternatives you've considered**

It seems possible to use:

https://renkulab.io/gitlab/cchoirat/rpath/blob/master/entrypoint.sh#L22-25
https://renkulab.io/gitlab/cchoirat/rpath/blob/master/Dockerfile#L18

But, I'm not sure what's get copied in the Docker image:

https://renkulab.io/gitlab/cchoirat/rpath/blob/master/entrypoint.sh#L31-36

**Comment by rokroskar** [comment]
I don't understand the question - are you asking about what that second set of lines is doing?

**Comment by cchoirat** [comment]
I mean it does work, but I'm wondering if information is passed in a Renku-templatable way.

**Comment by rokroskar** [comment]
That part copies your environment files from a repo called `renku-env` in gitlab. It's not related to the changes you are making afaik?

But in your code, you still have `rpath` which is not generic - shouldn't it be `${CI_PROJECT)` instead?

**Comment by cchoirat** [comment]
Tried in https://renkulab.io/gitlab/cchoirat/rpath/commit/bf751b95528c2a8412540862b57681d490987386
but didn't work (reverts to the current behavior).

**Comment by rokroskar** [comment]
I think you have a typo - that line should be:

```
echo /home/rstudio/${CI_PROJECT}/${CI_PROJECT}.Rproj | tee /home/rstudio/.rstudio/projects_settings/next-session-project
```

(regular braces instead of curly braces after the second `$CI_PROJECT`)

**Comment by cchoirat** [comment]
Indeed, thanks @rokroskar!

This being said, the `.Rproj` file is typically `$CI_PROJECT` `.Rproj`, but not all the time.

So, if say, `rpath.Rproj` doesn't exist, we could check whether another `.Rproj` file is available.

**Comment by emmjab** [comment]
closing with https://github.com/SwissDataScienceCenter/renku-jupyter/pull/67

Solved this by providing a default .Rproj with the contents equivalent to what R usually puts in this file by default.
