### ISSUE TITLE
docs: update Renku history on readthedocs

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#736]
The [history section](https://renku.readthedocs.io/en/latest/introduction/index.html#history) on the Renku readthedocs has not been updated for a long time.

**Comment by rokroskar** [comment]
Do we need it? We have the changelog.

**Comment by emmjab** [comment]
We don't have the changelog in the renku docs, just in renku-python? (or maybe we do, but I couldn't find it on first glance).

**Comment by ableuler** [comment]
> Do we need it? We have the changelog.

I agree, just linking to the changelog makes more sense. This information would be outdated all the time.

**Comment by ableuler** [comment]
> We don't have the changelog in the renku docs, just in renku-python? (or maybe we do, but I couldn't find it on first glance).

We can just link to the repo changelog I would say.

**Comment by rokroskar** [comment]
Or we can convert the changelog to RST and link it in to the docs directly. Either way I agree that the history section probably needs to go and whatever is there that is not in the changelog should be added to the changelog for posterity.

**Comment by gavin-k-lee** [comment]
I think the history section has been removed - so is this issue effectively closed?
