### ISSUE TITLE
Allow users to kill unschedulable pods

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku#745]
**Is your feature request related to a problem? Please describe.**
When a user pod can not be scheduled - for example due to unavailable resources - there is not way for the user to kill this pod.

**Describe the solution you'd like**
The UI should notify about an unschdulable state and give the user the opportunity to delete the pod.

**Comment by rokroskar** [comment]
This functionality is waiting for https://github.com/SwissDataScienceCenter/renku-notebooks/pull/215

**Comment by gavin-k-lee** [comment]
Effectively solved? Since https://github.com/SwissDataScienceCenter/renku-notebooks/pull/215 was closed

**Comment by lorenzo-cavazzi** [comment]
Not fixed yet. Currently, unschedulable pods are removed automatically after a timeout (5 mins iirc), but the user can't manually kill an unstarted pod.
Here is a recap https://github.com/SwissDataScienceCenter/renku-notebooks/issues/62#issuecomment-600120074

**Comment by olevski** [comment]
After switching to Amalthea and https://github.com/SwissDataScienceCenter/renku-ui/pull/1605 this can be closed.
