### ISSUE TITLE
[docs] Improve flights tutorial documentation

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku#833]
The following is a list of small fixes that could improve the [first steps flights tutorial](https://renku.readthedocs.io/en/latest/user/firststeps.html).

* "The advantage of data in a data repository is that it can contain metadata that can be used to help interpret it. " where is this metadata ?

*  "And we need to capture this change in git." --> add something like: so that next time we start the environment the packages are installed already

* git commit -m"Installed pandas and seaborn" missing space after -m, similar later

* "When an updated requirements.txt file is pushed to renkulab, renkulab will rebuild the software stack used for the interactive environments. If you shut down an interactive environment, the next time you start a new one, the packages specified in requirements.txt will already be available in the new environment." --> after this or around this section put a note on how/where to check for errors in case the image does not build, explain link with image build 

* tutorial looks too long as is and some sections might be optional, we could probably use expanding sections

* on errors accidentally? hide or put a FAQ below. 

* "You can undo your changes with" is repeated twice 

* I would maybe take out the error part in the first steps, is fine for a workshop or tutorial but not for first steps which I think should be more concise

* The tutorial documentation in general is too long. In my opinion, this could be fixed with some wording and reorganization

**Comment by rokroskar** [comment]
@pameladelgado could you make a PR with the suggested changes?
