### ISSUE TITLE
firststeps page is missing

### ISSUE THREAD

**Issue by lgatto** [SwissDataScienceCenter/renku#875]
**Describe the bug**

Dead link to tutorial

**To Reproduce**
1. Go to https://renkulab.io/
2. Click on the link in "If you are here for your first time, we recommend you go through our [tutorial](https://renku.readthedocs.io/en/latest/user/firststeps.html)." 
3. Get "SORRY This page doesn't exist"

The dead link is: https://renku.readthedocs.io/en/latest/user/firststeps.html

**Screenshots and/or execution output**
If applicable, add screenshots and/or execution output to help explain your problem.

![2020-03-11-065105_961x670_scrot](https://user-images.githubusercontent.com/384198/76386452-d46cc900-6364-11ea-86e2-65691f5e7eb1.png)

![2020-03-12-063928_892x914_scrot](https://user-images.githubusercontent.com/384198/76490786-4b20c980-642c-11ea-8e53-e0c059f00398.png)

**Comment by lorenzo-cavazzi** [comment]
Thanks for reporting this issue and for all the details.
The correct link has recently changed to https://renku.readthedocs.io/en/latest/tutorials/firststeps.html 
We will update it very soon.

**Comment by rokroskar** [comment]
This has been fixed - thanks @lgatto for opening the issue!
